### ISSUE TITLE
Feature Request: Make dependencies on the different providers json-smart, jackson, gson optional

### ISSUE THREAD

**Issue by forsthofer** [jayway/JsonPath#101]
The current 2.0.0 version has in the OSGi manifest mandatory imports for the different JSON providers:
com.fasterxml.jackson.core;version="[2.4,3)",
com.fasterxml.jackson.databind;version="[2.4,3)",
com.fasterxml.jackson.databind.type;version= "[2.4,3)",
com.google.gson;version="[2.3,3)",
com.google.gson.internal; version="[2.3,3)",
com.google.gson.reflect;version="[2.3,3)",
net.minidev.json;version="[2.1,3)",
net.minidev.json.parser;version="[2.1,3)",
net.minidev.json.writer;version="[2.1,3)"

It would be great to make all these dependencies optional, so that the OSGi bundle gets resolved without all the JSON providers. Of course you have to provide at least one provider to be able to run jasonpath successfully. However, this solution would be much leaner.

Beside the changes in the manifest file, also changes in the DefaultsImpl must be made. This class must be made more flexible: If the json-smart provider is not in the classpath, this class could  look for providers which are in the classpath and use the first found provider.

If you which I can create a pull request.

**Comment by forsthofer** [comment]
I found out that changes in DefaultsImpl are not necessary. You just have to set an other Default instance in the configuration before the first call is made.

**Comment by kallestenflo** [comment]
Fixed for 2.1.

**Comment by jochenberger** [comment]
I don't think we should make/have made json-smart optional. See #274, #314.
