### ISSUE TITLE
How to obtain a list of all xpaths from a json document

### ISSUE THREAD

**Issue by robinroos** [jayway/JsonPath#104]
Sorry to create an Issue, but I could not find a Forum.  

I wish to parse Json documents and turn them into tables for use in Fitnesse tests.  To do this I considered obtaining the list of all definite (canonical?) json-path expressions, which would form the left-hand column of the table, and then evaluating each path expression in turn to fill in the right-hand column.

In Fitnesse I could then constrain that a specific json-path matched the expected node value.  I could also see what "supurfluous" node values existed in the document (otherwise I would just invoke individual xpath expressions in turn without ever having to know the full set of path expressions availabls in a given document.

So, any hints as to how to establish the full canonical set of json-path expressions realized in a given json document?

Thanks, Robin.

**Comment by kallestenflo** [comment]
There is a group for questions https://groups.google.com/forum/#!forum/jsonpath

Not sure I understand what you want.

```java
Configuration configuration = Configuration.defaultConfiguration().addOptions(Option.AS_PATH_LIST);
List<String> allJsonPaths = JsonPath.using(configuration).parse(json).read("$..*");
```

returns 

```javascript
[
   "$['store']",
   "$['expensive']",
   "$['store']['book']",
   "$['store']['bicycle']",
   "$['store']['book'][0]",
   "$['store']['book'][1]",
   "$['store']['book'][2]",
   "$['store']['book'][3]",
   "$['store']['book'][0]['category']",
   "$['store']['book'][0]['author']",
   "$['store']['book'][0]['title']",
   "$['store']['book'][0]['price']",
   "$['store']['book'][1]['category']",
   "$['store']['book'][1]['author']",
   "$['store']['book'][1]['title']",
   "$['store']['book'][1]['price']",
   "$['store']['book'][2]['category']",
   "$['store']['book'][2]['author']",
   "$['store']['book'][2]['title']",
   "$['store']['book'][2]['isbn']",
   "$['store']['book'][2]['price']",
   "$['store']['book'][3]['category']",
   "$['store']['book'][3]['author']",
   "$['store']['book'][3]['title']",
   "$['store']['book'][3]['isbn']",
   "$['store']['book'][3]['price']",
   "$['store']['bicycle']['color']",
   "$['store']['bicycle']['price']"
]
```

You can try it out here http://jsonpath.herokuapp.com
