### ISSUE TITLE
	Member names containing dot fail

### ISSUE THREAD

**Issue by tangjwtj** [jayway/JsonPath#111]
when member names containing dot , jsonpath not work properly, for example:
{"resultMap":{
    "accessPoint.uri":"https://xxx
    "accessPoint.password":"yyy",
    "accessPoint.username":"zzz",
    "accessPoint.category.name":"URL"
}}

use jsonpath :$.resultMap.'accessPoint.uri'  can't get result.

**Comment by kallestenflo** [comment]
You must use bracket notation:

`$.resultMap.['accessPoint.uri']`

**Comment by kallestenflo** [comment]
Use bracket notation.
