### ISSUE TITLE
Add hamcrest-matchers based on JsonPath expressions

### ISSUE THREAD

**Issue by helsing** [jayway/JsonPath#119]
Are there any others that would love to have hamcrest-matchers based on JsonPath?

I would like to express my tests like this:

    assertThat(json, hasJsonPath("$.store.book[*].author", equalTo("Nigel"));

Currently I need to implement something similar to below in my projects, but I would prefer if it was already provided in the json-path library in some different flavors depending on usage.

    public static <T> Matcher<String> hasJsonPath(final String path, Matcher<? super T> matcher) {
        return new TypeSafeMatcher<String>() {
            @Override
            protected boolean matchesSafely(String json) {
                return matcher.matches(com.jayway.jsonpath.JsonPath.read(json, path));
            }

            @Override
            public void describeTo(Description description) {
                description.appendText("has json path ").appendValue(path).appendText(" ").appendDescriptionOf(matcher);
            }
        };
    }

**Comment by helsing** [comment]
I added a repo with a draft implementation, https://github.com/helsing/hamcrest-json-path. Let me know if you want me to provide a pull request on JsonPath, or if you think it would be more suitable to publish as a completely separate artifact? I am thinking it would be good to have the matchers both in hamcrest-1.3 flavor, and in hamcrest-2.0 flavor. WDYT?

**Comment by kallestenflo** [comment]
I don't want a Hamcrest dependency in the json-path core project. On the other hand there is json-path-assert that is similar in functionality to what you are providing (ignore the deprecations they will be removed in 2.1.1). This project already depends Hamcrest. The project has not been developed much over the years so if you wold like to contribute it would appreciated. Sprig uses json-path in some of their test frameworks (http://spring.io/guides/tutorials/bookmarks/) so it would be nice to align the implementation.

Personally I prefer AssertJ over Hamcrest and would like to provide a plugin.

**Comment by helsing** [comment]
Well, hamcrest only supports (and should only support) the actual matching (like a Predicate with descriptions). If I use matchers for testing, filtering, input validation or assertions, is out-of-scope for hamcrest. AssertJ may be good, but has limited use. I would prefer separating the matching from the semantics of that matching. Do you think it would be valuable to add a json-path-hamcrest module? That module could then possibly be used to implement the json-path-assert module, if you like?

**Comment by kallestenflo** [comment]
Why a new module? Why not add it to json-path-assert? Naming issue?

**Comment by helsing** [comment]
Well, yes, naming :-) Good to clarify the intention. Is json-path-matchers, better?

**Comment by kallestenflo** [comment]
I agree that the naming is important but so is keeping the number of dependencies down, transitive ones included. There are quite a few project that depend on json-path-assert.

One thing that it is important is that json-path-assert is be based on the new matchers - where ever they end up.

Can we push the final module/naming decision ahead of us for a while. And yes, json-path-matchers is better :)

**Comment by drekbour** [comment]
I have written a few hasJsonPath matchers based on this project. Will look forward to testing an official replacement!

**Comment by kallestenflo** [comment]
Hope to release version 2.2 with hamcrest-matcher support in early March.
