### ISSUE TITLE
Json path query is not working as expected

### ISSUE THREAD

**Issue by harishpalepu** [jayway/JsonPath#120]
JSON :
{
    "key" : "value",
    "array" : 
        { "key" : 1 },
        { "key" : 2, "dictionary": {
                "a": "Apple",
                "b": "Butterfly",
                "c": "Cat",
                "d": "Dog"
            } },
        { "key" : 3 }
    ]
}

Extraction Query:
$.array[?(@.key=2)].dictionary.b

Result:
[
    "Butterfly"
]

Im trying using your library giving an output of empty list

validationObj.jsonPath ="$.array[?(@.key=2)].dictionary.b" 

JsonPath.read(responseJSONData, validationObj.jsonPath) -->[ ] instead of ["Butterfly"] 

Please your help is appreciated

**Comment by frmichel** [comment]
Hi, just as an information I guess this is related to one of the concerns I've raised in this issue: https://github.com/jayway/JsonPath/issues/114

**Comment by warwickhunter** [comment]
Here is the correctly formatted JSON.

{
  "key": "value",
  "array": [
    {
      "key": 1
    },
    {
      "key": 2,
      "dictionary": {
        "a": "Apple",
        "b": "Butterfly",
        "c": "Cat",
        "d": "Dog"
      }
    },
    {
      "key": 3
    }
  ]
}

I think this expression gives the answer you seek.

$.array[?(@.key==2)].dictionary.b


On 9 September 2015 at 16:13, Franck Michel <notifications@github.com>
wrote:

> Hi, just as an information I guess this is related to one of the concerns
> I've raised in this issue: #114
> <https://github.com/jayway/JsonPath/issues/114>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jayway/JsonPath/issues/120#issuecomment-138796657>.
>



-- 
Warwick Hunter
K1300S/R1200GSA m: +61 4 1242 1576 skype: warwickhunter
