### ISSUE TITLE
Configuration builder forces dependency on Minidev json-smart

### ISSUE THREAD

**Issue by escardin** [jayway/JsonPath#121]
In the configuration builder, it always calls getEffectiveDefaults, even when it is unnecessary. If you have not set the defaults, but have set both jsonProvider and mappingProvider, the call to getEffectiveDefaults is unnecessary, and only serves to introduce a dependency.

This is a problem when you are another library. You do not want to override the defaults, because the users of your library might be depending on those defaults. However, you have your own providers set, such that the defaults will not be used, ensuring safe operation.

**Comment by escardin** [comment]
A fix could be:

    public Configuration build() {
        if (null == jsonProvider || null == mappingProvider) {
            Defaults defaults = getEffectiveDefaults();
            if (jsonProvider == null) {
                jsonProvider = defaults.jsonProvider();
            }
            if (mappingProvider == null) {
                mappingProvider = defaults.mappingProvider();
            }
        }
        return new Configuration(jsonProvider, mappingProvider, options, evaluationListener);
    }

**Comment by escardin** [comment]
Related issue: https://code.google.com/p/json-path/issues/detail?id=68

**Comment by kallestenflo** [comment]
Fixed in #128
