### ISSUE TITLE
How to get child of parent while filtering by neighbor of this child object ?

### ISSUE THREAD

**Issue by PositiveAlex** [jayway/JsonPath#123]
How can I get *value* parameter of an item in *chilren* list using the *code* parameter ?

I found only one way to do this and I dont like it:

*$.children.[?(@.info.code == 'code1')]..value*

I dont like that the filter expression does not iterate recursively using double dots like 

*$.children.[?(@..code == 'code1')]..value* -- this sentence gives me an error.

Is there any way to get *value* using shorter expression and in more elegant way?
Because it's an example, on real world parameter names can be way longer. and the structure itself may be deeper so I need to write shorter queries.

```json
{
	"object": {
		"children": [
			{
				"info": {
					"id": "1",
					"code": "code1"
				},
				"values": [
					{
						"value": "test"
					}
				]
			},
			{
				"info": {
					"id": "2",
					"code": "code2"
				},
				"values": [
					{
						"value": true
					}
				]
			}
		]
	}
}
```

**Comment by kallestenflo** [comment]
Currently there is no other way.

**Comment by PositiveAlex** [comment]
Okay, someone will send a pull request then
