### ISSUE TITLE
IllegalArgumentException even when Config.SUPPRESS_EXCEPTIONS is set

### ISSUE THREAD

**Issue by LesNovell** [jayway/JsonPath#124]
```
            Configuration config = Configuration.defaultConfiguration()
                    .addOptions(Option.SUPPRESS_EXCEPTIONS)
                    .addOptions(Option.ALWAYS_RETURN_LIST)
                    .addOptions(Option.DEFAULT_PATH_LEAF_TO_NULL);
            DocumentContext parsedJson = JsonPath.using(config).parse("");
```

The above code will throw an IllegalArgumentException, because the string value being passed to parse is empty.  It was my expectation that SUPRESS_EXCEPTIONS option would supress all json parsing exceptions.  This is helpful when guarding an invalid input to parse(), and the IllegalArgumentException should not be thrown if SUPRESS_EXCEPTIONS config option is set.

**Comment by kallestenflo** [comment]
The SUPPRESS_EXCEPTIONS options is intended to suppress exceptions during path evaluation. Your path is not valid so the evaluation never starts. Maybe an InvalidPathException would be better?

**Comment by LesNovell** [comment]
It's the input Json document that is invalid... I thought this option
should prevent exceptions when the path in the Json document cannot be
found. For example, if the Json document is valid but empty. "{}"

If the Json document is invalid, the path still is failing to find its
target. It would be really helpful to suppress exceptions on an invalid
document ... Because usually the document is input from a service response
call. Maybe we're getting back some html error message with a 404?

Anyway this would help me avoiding wrapping JsonPath in a generic catch
throwable block which was my expectation.

**Comment by kallestenflo** [comment]
Sorry, of course it's the document that is invalid. However  this does not change the fact that the exception is thrown prior to the path evaluation. 

Can you explain your solution with some more details? What should be returned from the parse method and what should happen when you try to read a path from that object.

**Comment by kallestenflo** [comment]
Invalid JSON should throw an exception.

**Comment by gcbw** [comment]
From the point of view of the application using jsonPath, _it_ is all the same.

It received a String from somewhere, likely a REST call, all the application cares is if it can extract some value from a json path.

I guess my point to comment here, is: If the calling application do not care (via this option) if the JSON is malformed, why would it care if it is empty? I might be sending a JPEG base64 encoded or some 500 error html to this library, and that option would just let it continue happily. But somehow an empty string is an edge case :)
