### ISSUE TITLE
FIilter "toString()" and consequent "parse" fail

### ISSUE THREAD

**Issue by marcomezzanotte** [jayway/JsonPath#129]
Hi.

In order to Serialize a Filter object I tried to send it as the string result of Filter's toString() method.

I don't know how can I parse the string obtained as before in order to get the original Filter obj.

Is there a way to "Serialize" a filter obj?

Thanks.

**Comment by kallestenflo** [comment]
This has been improved in the upcoming release. It's not perfect but I hope to reimplement filters in the future.

**Comment by kallestenflo** [comment]
This works now. Check out the test for details 

JsonPath/json-path/src/test/java/com/jayway/jsonpath/FilterParseTest.java

The syntax for serializing custom operators may change before release.
