### ISSUE TITLE
Failed to parse "Infinity" and "-Infinity" to `Double.POSITIVE_INFINITY` and `Double.NEGATIVE_INFINITY`

### ISSUE THREAD

**Issue by alfonsomunozpomer** [jayway/JsonPath#130]
Hi, I’ve just came across this problem with v2.0.0. When parsing a JSON array of doubles such as the following:
```
{foldChanges: [
    { foldChange: "Infinity"},
    { foldChange: "-Infinity"},
    { foldChange: 3.54051821666666},
    { foldChange: -3.53462115}
]}
```

The following fails to create a list of `Double`, the two first elements are always a `String`:
```
List<Double> foldChanges = jsonReadContext.read("$.foldChanges[*].foldChange");
```

No matter the type of List that I choose, the first two values are always a `String` and the last two are `Double`. I would hope that an option could be included to make force some sort of type coercion. If somebody wants to parse the previous JSON you need to check if the read value is either a `String` or a `Double` first.

**Comment by kallestenflo** [comment]
Hi,
This would be a problem with the underlying JSON parser. If you are using the default JsonProvider I suggest you file an issue with Json-smart http://netplex.github.io/json-smart/. 

Try using Jackson or Gson JsonProvider.
