### ISSUE TITLE
Checking if Node Exists - Bracket Notation Syntax

### ISSUE THREAD

**Issue by dhuynh** [jayway/JsonPath#131]
Hi,

I currently have data file with rows of json objects containing information I want to extract.

Currently, there is a field called random which will sometimes appear in some of the data.

[1, 2, {"d": { "random":null, date: 1234} , "l": filler } ]

Using bracket notation, to check if a node exists, should the syntax not be:

```
$[2]['d'][?(@.random)]['date']
```

The filter checks if the node exists, and if it does, then the query will retrieve date. Is this the proper way to do it, or is there an underlying issue with bracket notation with jsonpaths. 

Thank you

**Comment by kallestenflo** [comment]
Hi,

There are several issues with how filters are handled when applied to objects. Not sure what the issue is and how it is supposed work. The reference implementation does not give all the answers. 

I need to look into this.

**Comment by dhuynh** [comment]
This is much appreciated.

Thank you.

**Comment by jochenberger** [comment]
I think the problem is that the value of `random` is `null`, which JsonPath interprets as "does not exist", see Criteria.java:395.

**Comment by jochenberger** [comment]
I think EXISTS should compare with `JsonProvider.UNDEFINED` instead of `null`. The problem was introduced in 290edb540c35034dd317edbb282f2685bbc15283.

**Comment by kallestenflo** [comment]
This works as expected now.
