### ISSUE TITLE
SUPRESS_EXCEPTIONS not working when document is parsed separately? 

### ISSUE THREAD

**Issue by pgoldweic** [jayway/JsonPath#136]
Depending on which approach I take to parse a json string with JsonPath (either parse the string every time for each path, or only once before paths are read), the SUPRESS_EXCEPTIONS option behaves differently. Specifically, it does not seem to work as expected if I use the "parse only once" approach.  Here are my two attempts:
(note: json is a json String representing an object with *no* 'comment' field value)
("parse only once" approach): 
1-  Configuration conf = Configuration.builder().options(Option.SUPPRESS_EXCEPTIONS,Option.DEFAULT_PATH_LEAF_TO_NULL).build();
Object document = conf.jsonProvider().parse(json);
String commentBody = JsonPath.read(document, "$.comment.body");

Produces: PathNotFoundException: Property ['body'] not found in path $['comment']
I would have expected no exception would be produced, which is what happens below: 

("parse for every path approach")
2- Configuration conf = Configuration.builder().options(Option.SUPPRESS_EXCEPTIONS,Option.DEFAULT_PATH_LEAF_TO_NULL).build();
String commentBody = JsonPath.using(conf).parse(json).read("$.comment.body");

This code does not produce any exceptions

Is this a bug or am I misunderstanding how SUPRESS_EXCEPTIONS is supposed to work?

**Comment by jochenberger** [comment]
In the first example, the configuration is not passed to the `read` call. You'd need to change the last line to `JsonPath.using(conf).read(document, "$.comment.body");`
Or you can do it like this:
```
Configuration conf = Configuration.builder().options(Option.SUPPRESS_EXCEPTIONS,Option.DEFAULT_PATH_LEAF_TO_NULL).build();
DocumentContext ctx = JsonPath.using(conf).parse(json);
String commentBody = ctx.read("$.comment.body");
```

**Comment by kallestenflo** [comment]
To get the first example to work you must set the default configuration
```java
Configuration.setDefaults(new Configuration.Defaults() {

    private final JsonProvider jsonProvider = new JacksonJsonProvider();
    private final MappingProvider mappingProvider = new JacksonMappingProvider();
    private final Set<Option> options = 
                  EnumSet.of(SUPPRESS_EXCEPTIONS, DEFAULT_PATH_LEAF_TO_NULL);
    @Override
    public JsonProvider jsonProvider() {
        return jsonProvider;
    }

    @Override
    public MappingProvider mappingProvider() {
        return mappingProvider;
    }

    @Override
    public Set<Option> options() {
        return options;
    }
});
```

**Comment by pgoldweic** [comment]
Thank you both for your replies. Glad that there is a way to get this to work!
