### ISSUE TITLE
Function "JsonPath.getList()" returns null when key contains a hyphen "-"

### ISSUE THREAD

**Issue by joshdk** [jayway/JsonPath#140]
Hello,

I am pulling in `com.jayway.restassured:json-path:2.6.0` as a dependency of `com.jayway.restassured:rest-assured:2.6.0` (which is fantastic by the way!). When attempting to validate some properties of a JSON API, I ran into the following case, which looks like a bug.

Given a JSON document like `{"key-name":["value1", "value2"]}`, I can call `JsonPath.getString("\"key-name\"[0]")` to get the first list value `value1`.

**But**, if instead I ask for the entire list with `JsonPath.getList("\"key-name\"")`, I just get `null` instead.

I have validated my syntax using other JSONPath parsers (like https://jsonpath.curiousconcept.com/) and everything looks correct. I have also included sample code below that shows how my syntax **works for key with underscores**, but **fails for keys with hyphens**.

```java
import com.google.common.collect.ImmutableList;
import com.jayway.restassured.path.json.JsonPath;
import org.junit.Assert;
import org.junit.Test;

public final class JsonTest {

    @Test
    public void testParse() {
        String body;
        JsonPath json;

        // Original JSON, notice that the key contains an underscore
        body = "{\"key_name\":[\"value1\", \"value2\"]}";
        json = new JsonPath(body);

        // Assert #1 passes
        Assert.assertEquals(
            "value1",
            json.getString("key_name[0]")
        );

        // Assert #2 passes
        Assert.assertEquals(
            "value1",
            json.getString("\"key_name\"[0]")
        );

        // Assert #3 passes
        Assert.assertEquals(
            ImmutableList.of("value1", "value2"),
            json.getList("\"key_name\"")
        );

        // Same as original JSON, notice that the key contains a hyphen instead of an underscore
        body = "{\"key-name\":[\"value1\", \"value2\"]}";
        json = new JsonPath(body);

        // Assert #4 passes
        Assert.assertEquals(
            "value1",
            json.getString("\"key-name\"[0]")
        );

        // Assert #5 fails
        //java.lang.AssertionError: expected:<[value1, value2]> but was:<null>
        Assert.assertEquals(
            ImmutableList.of("value1", "value2"),
            json.getList("\"key-name\"")
        );
    }

}
```

If there is a workaround that allows me to extract the desired values, that would also be great, as it's completely possible that I'm not escaping something properly.

Thank you!

**Comment by kallestenflo** [comment]
Wrong project.

https://github.com/jayway/rest-assured

**Comment by joshdk** [comment]
Bug has been migrated to the correct repo (jayway/rest-assured/issues/601)

I now see that the class manifests don't match up (`com.jayway.restassured:json-path` versus `com.jayway.jsonpath:json-path`) that being said, can you please expound on the differences between these two (similarly named) projects? (for new-user eduction and historical purposes)

**Comment by kallestenflo** [comment]
The projects, JsonPath and RestAssured, where started at about the same time. At the time this JsonPath implementation was very rudimental and far from feature complete. The Rest-assured project decided to add a groovy  dependency and use JsonSlurper to query JSON documents. It was a bad choice by the RestAssured project to call it JsonPath. First and foremost because it's not a JsonPath implementation and secondly it collided with an other Jayway project (this one). Unfortunately these decisions are hard to revert.
