### ISSUE TITLE
JsonPath.read() ignores REQUIRE_PROPERTIES config option when AS_PATH_LIST is set

### ISSUE THREAD

**Issue by bradleymorris** [jayway/JsonPath#143]
**Description**
When I specify this (Note: REQUIRE_PROPERTIES is NOT set):
`Configuration jsonCfg = Configuration.builder().options( Option.AS_PATH_LIST ).build();`

And do this:
```java
String jsonStr = "{ \"foo\": { \"bar\" : \"val\" }, \"moo\": { \"cow\" : \"val\" } }";
Predicate[] predicates = {};
DocumentContext dCtx = JsonPath.using( jsonCfg ).parse( jsonStr );
readPaths = dCtx.read( JsonPath.compile( "$.*.bar", predicates ) );
```

**Actual Behaviour**
I get this:

```java
Exception in thread "main" com.jayway.jsonpath.PathNotFoundException: No results for path: $['moo']['bar']
	at com.jayway.jsonpath.internal.token.PathToken.handleObjectProperty(PathToken.java:53)
	at com.jayway.jsonpath.internal.token.PropertyPathToken.evaluate(PropertyPathToken.java:44)
	at com.jayway.jsonpath.internal.token.PathToken.handleObjectProperty(PathToken.java:71)
	at com.jayway.jsonpath.internal.token.WildcardPathToken.evaluate(WildcardPathToken.java:32)
	at com.jayway.jsonpath.internal.token.RootPathToken.evaluate(RootPathToken.java:53)
	at com.jayway.jsonpath.internal.CompiledPath.evaluate(CompiledPath.java:53)
	at com.jayway.jsonpath.internal.CompiledPath.evaluate(CompiledPath.java:61)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:176)
	at com.jayway.jsonpath.internal.JsonReader.read(JsonReader.java:146)
```
**Expected Behaviour**
I expected a `List` result containing a single path: `$[foo].[bar]` because I did not have the REQUIRE_PROPERTIES option set.  I would only expect to see PathNotFoundException if REQUIRE_PROPERTIES was set.

**Comment by bradleymorris** [comment]
Forgot to mention, stepping through with the debugger, it is clear that REQUIRE_PROPERTIES is not being set by default.  When I submit the ReadContext.read() request, there is only a single config option in the list - AS_PATH_LIST.

**Comment by kallestenflo** [comment]
I tried this in version 2.0.0 and 2.1.0 and it works as expected

```java
@Test
public void issue_143() {
    String json = "{ \"foo\": { \"bar\" : \"val\" }, \"moo\": { \"cow\" : \"val\" } }";

    Configuration configuration = Configuration
              .builder()
              .options( Option.AS_PATH_LIST )
              .build();

    List<String> pathList = JsonPath
              .using(configuration)
              .parse(json)
              .read("$.*.bar");

    assertThat(pathList).containsExactly("$['foo']['bar']");
}
```

What version are you using?

**Comment by bradleymorris** [comment]
I am using 2.0.0.

**Comment by kallestenflo** [comment]
And the test I provided fails?

**Comment by bradleymorris** [comment]
Yes, this test fails.  I had to refactor the assertThat() line to:
Assert.assertThat(pathList, hasItem("$['foo']['bar']"));

...but it does not matter. I get precisely the same Exception and stack trace that I provided in the initial bug description when read() is called.

For the record, 'configuration.jsonProvider().getClass().getName()' tells me I am using the com.jayway.jsonpath.spi.json.JsonSmartJsonProvider.

**Comment by jochenberger** [comment]
The test works for me too both from Eclipse and shell. @bradleymorris, how do you run the test?

**Comment by bradleymorris** [comment]
I am running the test with a JUnit-natured run configuration in Eclipse.

**Comment by jochenberger** [comment]
I cannot reproduce this. Here's what I do (with current git master):
* open json-path project in eclipse
* open `com.jayway.jsonpath.old.IssuesTest`
* right-click on the class name and choose Run As -> JUnit Test
The test completes successfully, including the `issue_143` method.

**Comment by kallestenflo** [comment]
Can not reproduce
