### ISSUE TITLE
Comma in selectors

### ISSUE THREAD

**Issue by alfonsomunozpomer** [jayway/JsonPath#144]
It seems that JsonPath doesn’t support commas in queries such as the following:

```
$.phoneNumbers[?(@.type=='iPhone','home')].number
```

And we need to use the more verbose:

```
$.phoneNumbers[?(@.type=='iPhone' || @.type=='home')].number
```

I’m using the example data from http://jsonpath.com/ where you can check that both work.

Just a minor inconvenience that I noticed. Thaks for the good work!

**Comment by kallestenflo** [comment]
I don't think this is a valid predicate. 

When I tried this at http://jsonpath.com/  and it does not seem to matter what you type as second parameter
```
$.phoneNumbers[?(@.type=='iPhone', 'd')].number

'0' => "0123-4567-8888"
'1' => "0123-4567-8910"
```
Gives same result as
```
$.phoneNumbers[?(@.type=='iPhone', 'home')].number

'0' => "0123-4567-8888"
'1' => "0123-4567-8910"
```

**Comment by alfonsomunozpomer** [comment]
Oh, my mistake. I assumed it worked after reading the spec at http://goessner.net/articles/JsonPath/.
So, how does comma work when it is mentioned here?
 > | 	[,] 	Union operator in XPath results in a combination of node sets. JSONPath allows alternate names or array indices as a set.

**Comment by kallestenflo** [comment]
I thought this was referring to paths like:

```
$['store']['book'][0,1,2]['title']
$['store']['book'][0]['title', 'category']
```

**Comment by jochenberger** [comment]
`$.phoneNumbers[?(@.type in ['iPhone','home'])].number` should do the trick.

**Comment by jochenberger** [comment]
@kallestenflo IMO this should be closed.
