### ISSUE TITLE
java.lang.NoClassDefFoundError: org/jsonpath/JsonJar error with gradle

### ISSUE THREAD

**Issue by VictoWork** [jayway/JsonPath#147]
am using 
    'net.minidev:json-smart:2.1.1'
    'net.minidev:asm:1.0.2'
    "org.slf4j:slf4j-api:1.7.10"
    'com.jayway.jsonpath:json-path:2.0.0'
still getting the error java.lang.NoClassDefFoundError: org/jsonpath/JsonJar

**Comment by kallestenflo** [comment]
Required libraries can be found here https://github.com/jayway/JsonPath/releases

Please post questions here https://groups.google.com/forum/#!forum/jsonpath
