### ISSUE TITLE
ValueConverter in last version can not use

### ISSUE THREAD

**Issue by cellpacing** [jayway/JsonPath#150]

**Comment by kallestenflo** [comment]
Please be more specific!

**Comment by cellpacing** [comment]
in my pom.xml  I add 
<dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
            <version>2.0.0</version>
 </dependency>

but ValueConverter can not import 

I see the submission log, this class is recently submitted, I think it should be upgraded version

**Comment by kallestenflo** [comment]
This feature is not released. You will have to build it yourself or wait for a week or so until I release version 2.1

**Comment by cellpacing** [comment]
thank you
