### ISSUE TITLE
JsonPath parse json error in leaf

### ISSUE THREAD

**Issue by sumrise** [jayway/JsonPath#151]
This is the JSON:
```
{
"datas": {
    "selling": {
        "3": [
            26452067,
            31625950
        ],
        "206": [
            32381852,
            32489262
        ],
        "208": [
            458
        ],
        "217": [
            27364892
        ],
        "226": [
            30474109
        ]
    }
},
"status": 0
}
```
My path is         $.datas.selling['3','206'].*
And I want to get both of '3' and '206' data. Like this JSON:

[
    26452067,
    31625950,
    32381852,
    32489262
]
But now it is not working.The error message is

Multi properties can only be used as path leafs: $['datas']['selling']['3', '206']
My JsonPath version is 2.0.0. 
I remember it can run in low-level version like 0.9.1.
How can I do it?

**Comment by kallestenflo** [comment]
This works as you expect in upcoming release.
