### ISSUE TITLE
Interference with RestAssured

### ISSUE THREAD

**Issue by CyborTronik** [jayway/JsonPath#152]
I'm trying to use this lib in project and RestAssured in tests and I'm getting:
``` java.lang.NoClassDefFoundError: Could not initialize class com.jayway.restassured.RestAssured
```
This lib breaks the RestAssured.

**Comment by kallestenflo** [comment]
Sounds like you have a problem with RestAssured. What makes you think JsonPath causes the problem?

**Comment by CyborTronik** [comment]
I'm using rest assured and it works like a charm.
When I'm adding this dependency to be used in app RestAsured gets broken.

**Comment by kallestenflo** [comment]
OK, I will need some details

1. JsonPath version 
2. RestAssured version
3. Other libs on classpath?

If you could provide code to reproduce this issue it would be great help.

**Comment by kallestenflo** [comment]
Using versions:
```
dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.11'
    testCompile 'com.jayway.restassured:rest-assured:2.7.0'
    testCompile 'com.jayway.jsonpath:json-path:2.0.0'
}
```


This works just fine
```java
import com.jayway.jsonpath.JsonPath;
import com.jayway.restassured.RestAssured;
import com.jayway.restassured.response.Response;
import org.junit.Assert;
import org.junit.Test;

public class Issue152 {

    @Test
    public void JsonPath_and_RestAssured_can_coexist() {
        Response response = RestAssured.get("http://jsonplaceholder.typicode.com/posts");
        String json = response.asString();
        String title = JsonPath.parse(json).read("$[0].title");
        Assert.assertEquals("sunt aut facere repellat provident occaecati excepturi optio reprehenderit", title);
    }
}
```

**Comment by CyborTronik** [comment]
Download https://github.com/CyborTronik/fluent-registry
Go to `service` module and add dependency there and do `mvn clean install` 
You will need to have maven, jdk8 and docker installed

**Comment by kallestenflo** [comment]
If you can reproduce the error in a less complex environment it would be great... 
I have all components installed (not latest version) but your build fails and I don't have the time to dig in.
