### ISSUE TITLE
Allow double quotes as string delimiters

### ISSUE THREAD

**Issue by jochenberger** [jayway/JsonPath#154]
I use JsonPath in a Groovy environment. Single quotes are usually used as delimiters for "regular strings" and the dollar has a special meaning in a doubly quoted string.
Being able to write `'$.foo[?(@.bar == "x")]' ` would save me from escaping hell (currently, I'd have to write `'$.foo[?(@.bar ==  \'x\')]' ` or `"\$.foo[?(@.bar == 'x')]" `).

**Comment by jochenberger** [comment]
The Goessner and Boon implementations seem to support that.

**Comment by jochenberger** [comment]
See #155

**Comment by jochenberger** [comment]
This was only a part of the solution. `$["foo"]` is not supported yet.

**Comment by jochenberger** [comment]
Are we there yet? ;-)

**Comment by kallestenflo** [comment]
I think we are!
