### ISSUE TITLE
Cant extract values using deep scan and DEFAULT_PATH_LEAF_TO_NULL

### ISSUE THREAD

**Issue by javierpajaro** [jayway/JsonPath#156]
Applying $.data[*]..['id','gasolina_93'] to the following json at http://jsonpath.herokuapp.com/?path= works great when setting Return null for missing leaf. Results are included at the end.

But doing the same using json-path(setting DEFAULT_PATH_LEAF_TO_NULL ) returns an empty json array 

Can you try and tell me if I am doing something wrong? Thanks.

{ "estado": "OK", "descripcion-estado": "OK", "serie": "Precios de combustibles liquidos en estaciones de servicio", "unidades": "Pesos por litro ($/l)", "fuente": "Sistema de Informacion en Linea de Precios de Combustibles en Estaciones de Servicio de la Comision Nacional de Energia - Departamento de Hidrocarburos", "ult. actualizacion": "24-11-2015", "importante": "La veracidad y exactitud de los precios de los combustibles publicados en el presente sitio web son de exclusiva responsabilidad de los operadores de las estaciones de servicio informantes, en cumplimento de lo dispuesto en la Resolucion Exenta CNE Nro 60 del 30 de enero 2012. La Comision Nacional de Energia solo publica la informacion recibida en linea y no es responsable del contenido, precision ni oportunidad de la misma", "data": [ { "id": " te912002", "fecha": "2015-11-19 16:50:55", "direccion_calle": "ISABEL RIQUELME", "direccion_numero": "403", "latitud": -39.275088655248, "longitud": -72.237553596497, "nombre_comuna": "Villarrica", "nombre_distribuidor": "Sin Bandera", "tienda_conveniencia": "", "farmacia": "", "bano_publico": "", "servicios_mantencion": "", "autoservicio": "", "horario_atencion": "24 Hrs", "precio_por_combustible": { "gasolina_93": 728, "petroleo_diesel": 533, "gasolina_95": 776 }, "metodos_de_pago": { "efectivo": "1" } }, { "id": "ab1010102", "fecha": "2015-11-23 19:45:25", "direccion_calle": "MAXIMILIANO URIBE", "direccion_numero": "2067", "latitud": -41.478224, "longitud": -72.9830206, "nombre_comuna": "Puerto Montt", "nombre_distribuidor": "ABASTIBLE", "tienda_conveniencia": "", "farmacia": "", "bano_publico": "", "servicios_mantencion": "", "autoservicio": "", "horario_atencion": "HH", "precio_por_combustible": { "glp_vehicular": 409 }, "metodos_de_pago": { "efectivo": "1" } }, { "id": "ab1050101", "fecha": "0000-00-00 00:00:00", "direccion_calle": "rene schneider", "direccion_numero": "3620", "latitud": -39.8474886, "longitud": -73.2187286, "nombre_comuna": "Valdivia", "nombre_distribuidor": "ABASTIBLE", "tienda_conveniencia": "", "farmacia": "", "bano_publico": "", "servicios_mantencion": "", "autoservicio": "", "horario_atencion": "hh", "precio_por_combustible": { "": 0 }, "metodos_de_pago": { "": "1" } }, { "id": "ab1050102", "fecha": "0000-00-00 00:00:00", "direccion_calle": "pedro aguirre cerda", "direccion_numero": "1389", "latitud": -39.7956934, "longitud": -73.2131779, "nombre_comuna": "Valdivia", "nombre_distribuidor": "ABASTIBLE", "tienda_conveniencia": "", "farmacia": "", "bano_publico": "", "servicios_mantencion": "", "autoservicio": "", "horario_atencion": "hh", "precio_por_combustible": { "": 0 }, "metodos_de_pago": { "": "1" } }, { "id": "ab1310101", "fecha": "2015-11-19 11:18:32", "direccion_calle": "santa elvira", "direccion_numero": "155", "latitud": -33.4582226, "longitud": -70.6313635, "nombre_comuna": "Santiago", "nombre_distribuidor": "ABASTIBLE", "tienda_conveniencia": "", "farmacia": "", "bano_publico": "", "servicios_mantencion": "", "autoservicio": "", "horario_atencion": "hh", "precio_por_combustible": { "glp_vehicular": 547 }, "metodos_de_pago": { "": "1" } }]}

Results returned at http://jsonpath.herokuapp.com/?path=
[
   {
      "id" : " te912002",
      "gasolina_93" : null
   },
   {
      "id" : null,
      "gasolina_93" : 728
   },
   {
      "id" : null,
      "gasolina_93" : null
   },
   {
      "id" : "ab1010102",
      "gasolina_93" : null
   },
   {
      "id" : null,
      "gasolina_93" : null
   },
   {
      "id" : null,
      "gasolina_93" : null
   },
   {
      "id" : "ab1050101",
      "gasolina_93" : null
   },
   {
      "id" : null,
      "gasolina_93" : null
   },
   {
      "id" : null,
      "gasolina_93" : null
   },
   {
      "id" : "ab1050102",
      "gasolina_93" : null
   },
   {
      "id" : null,
      "gasolina_93" : null
   },
   {
      "id" : null,
      "gasolina_93" : null
   },
   {
      "id" : "ab1310101",
      "gasolina_93" : null
   },
   {
      "id" : null,
      "gasolina_93" : null
   },
   {
      "id" : null,
      "gasolina_93" : null
   }
]

**Comment by kallestenflo** [comment]
What version of JsonPath are you using? The heroku version is running 2.1.0 that contains some bugfixes.

**Comment by javierpajaro** [comment]
Hi Kallestenflo,

I updated to the 2.1.0 version and now works in the same way than heroku.

But, may be there is a problem. When using .. to reach deep attributes, such atributes are returned in a new object. For example:

{
"id" : " te912002",
"gasolina_93" : null
},
{
"id" : null,
"gasolina_93" : 728
}

If you check the sample data, you will find that "gasolina_93": 728 belongs to the same object than "id":  " te912002".

Is that the what is expected or there is a bug?

**Comment by kallestenflo** [comment]
Yes it probably is a bug but it will never work. The multi property selector ['id','gasolina_93'] is not valid because 'id' is not in the same object as 'gasolina_93'. Typical usage of the multi property selector is to extract only certain properties form an object e.g `$['users'][*]['firstName', 'lastName']` where users is an array of user objects.

**Comment by javierpajaro** [comment]
'gasolina_93' is a property of 'precio_por_conbustible' object.

'precio_por_combistible' and 'id' are properties of the same object. That
is why I need $.data[*]..['id','gasolina_93'] to return both as if they
would belong to the same object.

Will that be supported or I would need to find another solution?

Regards,

**Comment by kallestenflo** [comment]
```javascript
 {   //Object A starts
            "id": " te912002",
            "fecha": "2015-11-19 16:50:55",
            "direccion_calle": "ISABEL RIQUELME",
            "direccion_numero": "403",
            "latitud": -39.275088655248,
            "longitud": -72.237553596497,
            "nombre_comuna": "Villarrica",
            "nombre_distribuidor": "Sin Bandera",
            "tienda_conveniencia": "",
            "farmacia": "",
            "bano_publico": "",
            "servicios_mantencion": "",
            "autoservicio": "",
            "horario_atencion": "24 Hrs",
            "precio_por_combustible": { //Object B starts
                "gasolina_93": 728,
                "petroleo_diesel": 533,
                "gasolina_95": 776
            },
            "metodos_de_pago": { //Object C starts
                "efectivo": "1"
            }
        }
```

`'id'` is in Object A
`'gasolina_93'` is in Object B

Not the same object.

`['id', 'direccion_calle']` is OK since both are in Object A

**Comment by javierpajaro** [comment]
I know they are not the same object.  But "precio_por_combustible" is a
property of object A, the same as "id"

Both objects are related to the same entity.
