### ISSUE TITLE
Accept Jackson's JsonNode and return List<JsonNode>

### ISSUE THREAD

**Issue by oleg-gr** [jayway/JsonPath#160]
This feature would be useful I think. Since you are internally using Jackson already

**Comment by kallestenflo** [comment]
This is supported by the JacksonJsonNodeJsonProvider.

**Comment by oleg-gr** [comment]
Well, JacksonJsonNodeJsonProvider will map the resulting value for you, but it won't actually return you the reference to the node. Unless I am misunderstanding the usage.

What I want to achieve is basically take a huge Json object and filter it down using path, but keeping the original structure. Can't seem to figure out how to achieve it with the current API. Suggestions?

**Comment by oleg-gr** [comment]
Maybe if there was an option to make `DocumentContext set(String path, Object newValue, Predicate... filters)` to not through `com.jayway.jsonpath.PathNotFoundException` and instead create missing properties, that would be useful

**Comment by kallestenflo** [comment]
There has been discussions about creating missing path elements but it has not been planed.

Is this not what you want?

```java
@Test
public void issue_160() {
  //will return reference
  ArrayNode arrayNode1 = using(JACKSON_JSON_NODE_CONFIGURATION)
        .parse(JSON_DOCUMENT)
        .read("$.store.book");

  //will create new ArrayNode holding references to original items. New array will 
  //be created by all path operations that are not definite. The array representation
  //created is decided by the JsonProvider 
  ArrayNode arrayNode2 = using(JACKSON_JSON_NODE_CONFIGURATION)
        .parse(JSON_DOCUMENT)
        .read("$.store.book[?(@.category == 'fiction')]");
  
  //will transform result according to type specification using JsonMappingProvider
  List<JsonNode> arrayNode3 = using(JACKSON_JSON_NODE_CONFIGURATION)
        .parse(JSON_DOCUMENT)
        .read("$.store.book[*]", new TypeRef<List<JsonNode>>(){});

  //will return reference
  ObjectNode objectNode = using(JACKSON_JSON_NODE_CONFIGURATION)
        .parse(JSON_DOCUMENT)
        .read("$.store.book[0]");

   //will return reference
  TextNode textNode = using(JACKSON_JSON_NODE_CONFIGURATION)
        .parse(JSON_DOCUMENT)
        .read("$.store.book[0].category");
}
```

**Comment by oleg-gr** [comment]
Thank you for the response.

Doing this
```
 ArrayNode arrayNode1 = using(JACKSON_JSON_NODE_CONFIGURATION)
        .parse(JSON_DOCUMENT)
        .read("$.store.book");
```
returns array node where each node is a string with a JsonPath. What I would want is an actual reference to the node at that path. The config that I am using is this:
```
Configuration.defaultConfiguration().jsonProvider(new JacksonJsonNodeJsonProvider()).mappingProvider(new JacksonMappingProvider());
```

Basically, if this is the input JSON:
```
{"hello":"hello_value","remove":{"this":"this value will be removed","and_this":"this value will also be removed"}}
```
then `JsonPath.using(JACKSON_JSON_NODE_CONFIGURATION).parse(JSON_DOCUMENT).read("$.remove")`  returns `["$['remove']"]` and not the reference to the node at `$.remove` path.

Am I missing something?

**Comment by kallestenflo** [comment]
>returns references, but any idea how to preserve original structure, e.g. have it return all the previous structure up to this leaf? Maybe somehow get JsonPointer?

Not sure I understand what want. When reading `"$.store.book"`  you don't want the `book`  ArrayNode? You want JsonPointers as result?

**Comment by oleg-gr** [comment]
@kallestenflo 
basically I want to be able to reconstruct 
```
{
  "store" : {
    "book" : book ArrayNode
  }
}
```
without having to parse "$.store.book" to reconstruct the object. Do you think it's possible?

**Comment by oleg-gr** [comment]
e.g. if I have
```
{
  "store" : {
    "book" : book ArrayNode,
    "bicycle" : bicycle ObjectNode,
    "doll" : doll ObjectNode
  }
}
```
I want to be able to get
```
{
  "store" : {
    "book" : book ArrayNode
  }
}
``` 
from "$.store.book"

as well as
```
{
  "store" : {
    "doll" : doll ObjectNode
  }
}
``` 
from "$.store.doll"

Do you see what I mean?

**Comment by cwensel** [comment]
I think what is being asked for (and I'm looking for) is a way to use JsonPath to match a sub-tree so it can be copied to a new position (on a new JsonObject) while preserving the structure. or removing the matched tree from the parsed json.

Using `Option.AS_PATH_LIST` is an option to get the tree, but the hope if a list of paths are returned, they match the ordered list of values returned from a standard `#read()` call. This is more frustrated by the need to parse the paths so the segments can be reconstructed.

**Comment by jsmiley208** [comment]
Is there are reason you need to map to a specific JsonNode Implementation instead of the JsonNode interface?
