### ISSUE TITLE
Using a filter expression with spaces/blanks

### ISSUE THREAD

**Issue by yrddraig** [jayway/JsonPath#161]
Given some json a bit like:

```
{
  "children": {
    "value": {
      "age": "10",
      "the cat": "jam",
      "thedog": "jam"
    }
  }
}
```

I can search for this record via 'thedog' by doing

```
$.children.value.[?(@.thedog=='jam')]
```

But how do I do it via the cat?  I know I can simply load it with

```
$.children.value.['the cat']
```

but I cannot do

```
$.children.value.[?(@.'the cat'=='jam')]
```

http://jsonpath.herokuapp.com/ says "Could not compile inline filter : [?(@.'the cat'=='jam')]"

This one doesn't seem to error:

```
$.children.value.[?('@.the cat'=='jam')]
```

but also doesn't return the record.  

Is this just not possible?

**Comment by kallestenflo** [comment]
If you have spaces or other strange stuff in you property names you must
use bracket notation ['foo bar']. This also applies in inline filters.

try this :

$.children.value[?(@['the cat'] == 'jam')]

**Comment by yrddraig** [comment]
That works.  I feel I must have tried every combination of ?(@. and ' except that one.  

Great job, thank you.  I can continue with JsonPath again
