### ISSUE TITLE
Number of issues in filters with literal parsing

### ISSUE THREAD

**Issue by zline** [jayway/JsonPath#162]
I expect this tests to pass, but it throw exceptions:

first, quoted string literal, escaped tick after escaped slash must be ignored:
`assertHasOneResult("[\"\\'foo\"]", "$[?(@ == '\\\\\\'foo')]", Configuration.defaultConfiguration());`

second, looks like escaping in patterns does't work:
`assertHasOneResult("[\"x\"]", "$[?(@ =~ /\\/|x/)]", Configuration.defaultConfiguration());`

and the last, there could be a problem in skipRegex code of CharacterIndex.indexOfMatchingCloseChar (it does't take escaping into account)
`assertHasOneResult("[\"x\"]", "$[?(@ =~ /\\/]|x/)]", conf);`

**Comment by kallestenflo** [comment]
>first, quoted string literal, escaped tick after escaped slash must be ignored:
assertHasOneResult("[\"\\'foo\"]", "$[?(@ == '\\\\\\'foo')]", Configuration.defaultConfiguration());

what is the property name evaluated here? `\\'foo`? Should there really be 6 slashes on the right or only 5?

**Comment by zline** [comment]
property name is slash, tick, foo (5 characters): `\'foo -> (after jsonpath escaping) -> \\\'foo` (extra slash for slash and for tick) and after java code escaping (each slash escaped, again): `\\\\\\'foo` , so 6 slashes.
btw, markdown engine has eat some slashes in quote text.

**Comment by kallestenflo** [comment]
OK, I have made some changes but I'm not sure I get it. Why do you have 6 slashes on the right side? 

Do you think the asserts below are wrong?
```java
assertHasOneResult("[\"\\'foo\"]", "$[?(@ == '\\'foo')]", conf);
assertHasOneResult("[\"\\\\'foo\"]", "$[?(@ == \"\\\\'foo\")]", conf);
```

**Comment by zline** [comment]
> Why do you have 6 slashes on the right side?

Property name (plain, without any escaping) consists of 5 characters: slash, apostrophe, word foo (1 slash total). To write this name inside jsonpath literal I have to escape both slash and apostrophe, like this: `\\\'foo` (3 slashes total). And finally, I want to write jsonpath expression inside java source string literal (double-quoted string), but still, I have to escape every slash inside double-quoted string. So 3 slashes double, producing 6 slashes.


> OK, I have made some changes but I'm not sure I get it. 

The problem with code was the following. It was insufficient to look at characters `readPosition - 1` and `readPosition - 2` to detect if character at `readPosition` is escaped or not, because we don't know if char at `readPosition - 2` is escaped. This routine had to be applied recursively, or as alternative we could keep memory "is current character escaped?" from the beginning of string, as you did using `inEscape` variable in ac83feea14f6b994b2a2afd6dc1b54e5d2f97404


> Do you think the asserts below are wrong?

It are correct. But I should note that first json (`["\'foo"]`) is incorrect according to json rfc because single apostrophe can not be escaped. But json-smart in default mode allows it.

**Comment by kallestenflo** [comment]
>It are correct. But I should note that first json (["\'foo"]) is incorrect according to json rfc because single apostrophe can not be escaped. But json-smart in default mode allows it.

Yes I noticed that Jackson throws exception. 

So this is solved now or do you see any other issues here?

**Comment by zline** [comment]
Looks like tests now fixed.
I'm sorry there is an error in my first test statement, it should be written as 
`assertHasOneResult("[\"\\\\'foo\"]", "$[?(@ == '\\\\\\'foo')]", Configuration.defaultConfiguration());`

As a side note I could say that I'd rather use depth-first approach to parsing: for example instead of searching for end-of-filter expression (`]`) I would allow expression parser to "eat" charsequence according to its syntax and then continue to parse filter (= require next char to be end-of-filter expression).

**Comment by kallestenflo** [comment]
I agree it would be better to use a depth-first approach. My plan is to provide a Path SPI where the parser can be configured. I think this is the way to go because I don't have the hours needed to put in and rely on pull requests. 

And again, thanks for the tests and feedback!
