### ISSUE TITLE
aggregate functions min() and max() return arbitrary (incorrect) values for an empty array

### ISSUE THREAD

**Issue by exbuddha** [jayway/JsonPath#168]
When I process the path "$.array.min()" or "$.array.max()" for the JSON object string below:

{ "array": [] }

I respectively get two incorrect values: 1.7976931348623157E308 and 4.9E-324

It seems that your algorithm starts off with the lowest and highest possible numbers and then tries to match those against array elements and update as it iterates through those elements. If that is the case, the solution would be to check the size of the array first and throw an error if it is empty (or take another action).

**Comment by mgreenwood1001** [comment]
Fix in PR #167

**Comment by jochenberger** [comment]
I guess this can just be closed as #167 added a fix as well as tests for this.
