### ISSUE TITLE
Can I use this library to 'flatten' and 'unflatten' a Jackson tree?

### ISSUE THREAD

**Issue by benson-basis** [jayway/JsonPath#176]
I'd like to start with a tree of Jackson JsonNode objects, and end up with a Map<String, Object> where the keys are paths and the values are the leaves of the tree.

And then I'd like to reverse the process; take such a map and end up with a tree. It seems as if this might be in the capacity of this library, but my first read didn't illuminate me.

**Comment by kallestenflo** [comment]
This is not supported in the current version.
