### ISSUE TITLE
'not exists' operator is not serialized in toString()

### ISSUE THREAD

**Issue by zline** [jayway/JsonPath#178]
I expect this test to pass:
`assertThat(compile("[?(!@.foo)]").toString()).isEqualTo("[?(!@['foo'])]");`

**Comment by jochenberger** [comment]
Not sure how this should be addressed. We could replace `?` by `predicate.toString()` in `com.jayway.jsonpath.internal.path.PredicatePathToken.getPathFragment()`, but even then you would get `"$[[?(@['foo'])]]"` and not `[?(!@['foo'])]`.

**Comment by jochenberger** [comment]
@kallestenflo Any thoughts on this?

**Comment by jochenberger** [comment]
@zline, what's your opinion on this?

**Comment by zline** [comment]
Maybe in `com.jayway.jsonpath.internal.filter.PathNode.toString()` in case of `isExistsCheck() && ! shouldExists()` we could `return '!' + path.toString();` .
Sorry for not providing a patch - I'm from phone at the moment.

**Comment by jochenberger** [comment]
Oh, right, you're talking about *`FilterCompiler.compile`* not about `PathCompiler.compile`...
