### ISSUE TITLE
could not get values from Json

### ISSUE THREAD

**Issue by gsaimadhu** [jayway/JsonPath#179]
My product is returning below like JSONs. 
Unable to parse the JSON using JSONPATH. Please help.
![jsonpath_error](https://cloud.githubusercontent.com/assets/8359360/12018283/cbd14b1a-ad86-11e5-9fc9-746b13ecc71a.jpg)
![jsonpath_error](https://cloud.githubusercontent.com/assets/8359360/12018327/3a70b8d0-ad87-11e5-884a-90142707842e.jpg)

Input:
{"result":[{"LGE":{"avg_cpu":26.0,"crash_count":0,"crash_count_percent":0.0,"http_errors":1,"http_errors_percent":100.0,"avg_mem":3.0,"affected_users":0,"affected_users_percent":0.0,"avg_session_length":4000,"avg_spin_time":-1,"avg_frame_rate":0.0,"avg_start_time":916,"spin_session_percent":0.0,"active_users":0,"sessions":1,"avg_battery":80.0,"counter":0,"http_errors_time":[["time_unit","count"],["2015-12-28 00:00:00",1]],"latency":[["time_unit","count"],["2015-12-28 00:00:00",45366]],"crashes":[["time_unit","count"],["2015-12-28 00:00:00",0]],"device":"LGE","deviceKey":0,"httpErrorsCount":null,"latencyCount":null,"crashCount":null}}],"per_page":10,"page":1,"total_records":1}

How to get values like avg_battery, etc?

**Comment by transparentech** [comment]
You can get avg_battery with this query:

$.result[0].LGE.avg_battery

You can get total_records with this query:

$.total_records

**Comment by gsaimadhu** [comment]
Thanks, getting the values :)

**Comment by gsaimadhu** [comment]
Thanks. The above Queries are working fine.

**Comment by gsaimadhu** [comment]
To tell -! Tree. -_+2.

,
TX..the . L
Thanks wear
