### ISSUE TITLE
Option to disable 'getjson' function.

### ISSUE THREAD

**Issue by dmihal** [jayway/JsonPath#180]
I see that #167 introduces the getjson function. While I can see the utility of the function, this opens up a huge security vulnerability if the provided jsonpath is not trusted. A user could use the getjson function to make nearly unlimited HTTP requests.

Could you add an option to the configuration to disable this feature? Thanks.

**Comment by kallestenflo** [comment]
The option should be disabled by default and require configuration to enable

`Option.ALLOW_HTTP_GET`

**Comment by jochenberger** [comment]
@kallestenflo Considering the "not intended to be merged" in the commit message of https://github.com/mgreenwood1001/JsonPath/commit/b919644425613279e01f08273767d8d23c6b011c and the latest comments on #167 (https://github.com/jayway/JsonPath/pull/167#issuecomment-185968312), I wonder if we should simply revert https://github.com/mgreenwood1001/JsonPath/commit/b919644425613279e01f08273767d8d23c6b011c. Or do you definitely want to keep the function?

**Comment by kallestenflo** [comment]
I agree that it can be dropped.

**Comment by jochenberger** [comment]
Okay, I'll put up a PR.
