### ISSUE TITLE
Regex for number and boolean value nodes

### ISSUE THREAD

**Issue by mchmielarz** [jayway/JsonPath#181]
There is no possibility to use regular expressions to match numeric and boolean values. This feature could be added to `RegexpEvaluator` by using node's `toString()` method instead of checking for a `ValueNode.StringNode`.

**Comment by mchmielarz** [comment]
Hi there, do you plan to add this feature to the project? I made PR for this and would like to know whether I should wait for it.

**Comment by kallestenflo** [comment]
Merged!
