### ISSUE TITLE
Negative of a regex in filter expression?

### ISSUE THREAD

**Issue by hammer2j2** [jayway/JsonPath#184]
I would like to do a filter which is a negative of a regex match.  I cannot seem to get it working.

for example:  the filter: `[?(@.region!~/.*-gov-.*/)]`

I've tried `[?(@.region!~/.*-gov-.*/)]` `[?(@.region!=~/.*-gov-.*/)]` and other variations trying to negate the regex and at best the expression runs, but either does not filter or returns no results.

Thanks for your help.

filterExpression = `'prefixes[*].[?(@.region!~/.*-gov-.*/)].ip_prefix'`

 DocumentContext dc = JsonPath.parse(json)

 List<String> subnets =  dc.read(filterExpression)

 json = jsonSlurper.parseText('''
{
    "createDate": "2015-12-23-20-22-16",
    "prefixes": [
        {
            "ip_prefix": "23.20.0.0/14",
            "region": "us-east-1",
            "service": "AMAZON"
        },
        {
            "ip_prefix": "46.51.128.0/18",
            "region": "eu-west-1",
            "service": "EC2"
        },
        {
            "ip_prefix": "96.127.0.0/17",
            "region": "us-gov-west-1",
            "service": "EC2"
        },
        {
            "ip_prefix": "46.51.192.0/20",
            "region": "eu-west-1",
            "service": "EC2"
        }
            ],
    "syncToken": "1450901537"
}''')

```
```

**Comment by arifogel** [comment]
If you want to simply math all things that do NOT match a regex, you can do e.g. ?(!(@.abc =~ /def/)) once my pull request #283 is merged.

**Comment by jonrodriguezb** [comment]
@hammer2j2 , have you solved this problem?

**Comment by jochenberger** [comment]
Will be supported in 2.3.0 (see #283)
