### ISSUE TITLE
Feature request: Make ParseContext from JsonPath.using thread safe

### ISSUE THREAD

**Issue by jgogstad** [jayway/JsonPath#187]
Hi,

We just found a race condition that's been bothering us for some while. Turned out it was a cached `com.jayway.jsonpath.ParseContext` that occasionally was called by several threads.

We assumed that we could parse configuration once, that is `JsonPath.using(Configuration.defaultConfiguration())`, and reuse that instance. I still think that would be nice.

**Comment by kallestenflo** [comment]
Fixed in version 2.3.0
