### ISSUE TITLE
In 2.1.0 not support @.length Filter ,but in 2.0.0 support

### ISSUE THREAD

**Issue by tangjwtj** [jayway/JsonPath#198]
In 2.0.0  support :

$.store.book[(@.length-2)].author   

but in 2.1.0 don't support .

**Comment by mika91** [comment]
Not working in 2.2.0 anymore.
It was very conveniant to get the last element of an array.

**Comment by jochenberger** [comment]
In the upcoming version, you'll be able to use negative array indexes, i.e. `$.store.book[-1].title` to get the last book's title.
