### ISSUE TITLE
JsonPath.json-path vs RestAssured.json-path

### ISSUE THREAD

**Issue by zkendall** [jayway/JsonPath#203]
What is the relationship between these two projects?

> https://github.com/jayway/JsonPath
> https://github.com/jayway/rest-assured/tree/master/json-path

I was chasing my tail for a while trying to get a path working with "$...[?(@.ABC =~..." only getting a strange error about EOF expected at "[". Eventually I realized the JsonPath I got back from a RestAssured response is an entirely different mechanism... Would be nice if the difference was noted somewhere at least.

**Comment by OnlyCookies** [comment]
Did you ever get a resolution to your issues? I've just stumbled across this very same issue and am now rummaging through webpages trying to find equivalent expressions for a "$...[?(@.ABC=='string')]" expression.

**Comment by kallestenflo** [comment]
There is no relationship between the projects. RestAssured JsonPath is based on Groovys JsonSlurper and is not compatible with the Gossner JSONPath specs.
