### ISSUE TITLE
BigDecimal is not supported

### ISSUE THREAD

**Issue by dinee432** [jayway/JsonPath#206]
Hi,

  My project uses some huge values to be passed and retrieved from Json. By default the numbers are considered as double. Is there any way to support bigdecimal?

Thanks,
Dinesh

**Comment by thekingnothing** [comment]
Maybe this could help you #76

**Comment by dinee432** [comment]
Hi,

 Even after using the smartconfiguration as specified, I am not able to get the bigdecimals without exponents.

Used the configuration : public static final Configuration JSON_SMART_CONFIGURATION = Configuration
        .builder()
        .mappingProvider(new JsonSmartMappingProvider())
        .jsonProvider(new JsonSmartJsonProvider(JSONParser.MODE_PERMISSIVE ^ JSONParser.USE_HI_PRECISION_FLOAT))
        .build();

Still I am getting 1.0000001E7 as a result instead of 10000000.90

Thanks,
Dinesh

**Comment by dinee432** [comment]
Posting a sample code
`final Configuration JSON_SMART_CONFIGURATION = Configuration
			        .builder()
			        .mappingProvider(new JsonSmartMappingProvider())
			        .jsonProvider(new JsonSmartJsonProvider(JSONParser. ^ JSONParser.USE_HI_PRECISION_FLOAT))
			        .build();
			String jsonPath=new String(
					Files.readAllBytes(Paths.get("FilePath")), 
						StandardCharsets.UTF_8);
			Object jsonPathResult = JsonPath.using(JSON_SMART_CONFIGURATION).parse(jsonPath).read("$.PayrollMasterData.PayrollDeployment.PayrollRemuneration.RemunerationAllocation[1].Amount");
			System.out.println("Value :"+ jsonPathResult.toString());`

**Comment by dinee432** [comment]
Created a custom Json provider and used it in the configuration.

**Comment by sebarys** [comment]
@dinee432 Could you share with us your custom configuration? 
Thanks!
