### ISSUE TITLE
jsonpath 2.2.0 - Invalid OSGi

### ISSUE THREAD

**Issue by davsclaus** [jayway/JsonPath#208]
The new release has invalid OSGi manifest.

When we upgrade camel-jsonpath to 2.2.0, then when installing we get this error

karaf@root()> feature:install camel-jsonpath
Error executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=camel-jsonpath; type=karaf.feature; version="[2.17.0.SNAPSHOT,2.17.0.SNAPSHOT]"; filter:="(&(osgi.identity=camel-jsonpath)(type=karaf.feature)(version>=2.17.0.SNAPSHOT)(version<=2.17.0.SNAPSHOT))" [caused by: Unable to resolve camel-jsonpath/2.17.0.SNAPSHOT: missing requirement [camel-jsonpath/2.17.0.SNAPSHOT] osgi.identity; osgi.identity=org.apache.camel.camel-jsonpath; type=osgi.bundle; version="[2.17.0.SNAPSHOT,2.17.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve org.apache.camel.camel-jsonpath/2.17.0.SNAPSHOT: missing requirement [org.apache.camel.camel-jsonpath/2.17.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.jayway.jsonpath.internal)(version>=2.1.0)(!(version>=3.0.0)))" [caused by: Unable to resolve com.jayway.jsonpath.json-path/2.2.0: missing requirement [com.jayway.jsonpath.json-path/2.2.0] osgi.wiring.package; filter:="(osgi.wiring.package=org.apache.tapestry5.json)"]]]

Notice that jsonpath imports org.apache.tapestry5.json. Which is NOT a dependency in the regular maven project

```
[INFO] ------------------------------------------------------------------------
[INFO] Building Camel :: JSon Path 2.17-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ camel-jsonpath ---
[INFO] org.apache.camel:camel-jsonpath:bundle:2.17-SNAPSHOT
[INFO] +- org.apache.camel:camel-core:jar:2.17-SNAPSHOT:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.13:compile
[INFO] +- com.jayway.jsonpath:json-path:jar:2.2.0:compile
[INFO] +- net.minidev:json-smart:jar:2.2.1:compile
[INFO] |  \- net.minidev:accessors-smart:jar:1.1:compile
[INFO] |     \- org.ow2.asm:asm:jar:5.0.3:compile
```

The OSGi bundle for 2.1.0 works in OSGi.

**Comment by davsclaus** [comment]
Maybe the intention is to make that option for that tapestry json, eg

```
Import-Package =
	org.json;resolution:=optional,
	com.google.gson;resolution:=optional;version="[2.3,3)",
	com.google.gson.internal;resolution:=optional;version="[2.3,3)",
	com.google.gson.reflect;resolution:=optional;version="[2.3,3)",
	com.fasterxml.jackson.core;resolution:=optional;version="[2.6,3)",
	com.fasterxml.jackson.databind;resolution:=optional;version="[2.6,3)",
	com.fasterxml.jackson.databind.node;resolution:=optional;version="[2.6,3)",
	com.fasterxml.jackson.databind.type;resolution:=optional;version="[2.6,3)",
	net.minidev.json;resolution:=optional;version="[2.2,3)",
	net.minidev.json.parser;resolution:=optional;version="[2.2,3)",
	net.minidev.json.writer;resolution:=optional;version="[2.2,3)",
	org.apache.tapestry5.json,
	org.slf4j;version="[1.7,2)"
```

Notice how all the others are marked as optional, but not tapestry in the bottom.

So to fix this make the line

```
	net.minidev.json.writer;resolution:=optional;version="[2.2,3)",
	org.apache.tapestry5.json:=optional;version="[5.4,6)",
```

**Comment by davsclaus** [comment]
It looks like you need to fix it by adding that tapestry to this line
https://github.com/jayway/JsonPath/blob/master/json-path/build.gradle#L12

**Comment by jochenberger** [comment]
See #207

**Comment by davsclaus** [comment]
Thanks @jochenberger

**Comment by iragreenstein** [comment]
Greetings,

My apologies if i should open a new issue for this.

I am making use of version 2.2.0, however sans camel.  Using the maven  dependency found in http://mvnrepository.com/artifact/com.jayway.jsonpath/json-path/2.2.0, i too am seeing that tapestry is not optional:

From the MANIFEST.MF

```
Manifest-Version: 1.0
Implementation-Title: json-path
Bundle-SymbolicName: com.jayway.jsonpath.json-path
Implementation-Version: 2.2.0
Bundle-ManifestVersion: 2
Bnd-LastModified: 1456761826000
Import-Package: 
    org.json;resolution:=optional,
    com.google.gson;resolution:=optional;version="[2.3,3)",
    com.google.gson.internal;resolution:=optional;version="[2.3,3)",
    com.google.gson.reflect;resolution:=optional;version="[2.3,3)",
    com.fasterxml.jackson.core;resolution:=optional;version="[2.6,3)",
    com.fasterxml.jackson.databind;resolution:=optional;version="[2.6,3)",
    com.fasterxml.jackson.databind.node;resolution:=optional;version="[2.6,3)",
    com.fasterxml.jackson.databind.type;resolution:=optional;version="[2.6,3)",
    net.minidev.json;resolution:=optional;version="[2.2,3)",
    net.minidev.json.parser;resolution:=optional;version="[2.2,3)",
    net.minidev.json.writer;resolution:=optional;version="[2.2,3)",
    org.apache.tapestry5.json,
    org.slf4j;version="[1.7,2)"
```
