### ISSUE TITLE
Error:duplicate entry: org/objectweb/asm/AnnotationVisitor.class

### ISSUE THREAD

**Issue by tialgalaq** [jayway/JsonPath#213]
I am using JSONPATH library in build.gradle
compile 'com.jayway.jsonpath:json-path:2.2.0'

When i build my project, it does not show any error. But when i run my project, it shows

Error:Execution failed for task '**:app:transformClassesWithJarMergingForDebug'.

com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/objectweb/asm/AnnotationVisitor.class**" error

but when i change json-path version as 1.1.0, it works well.

**Comment by kallestenflo** [comment]
This is a json-smart issue https://github.com/netplex/json-smart-v2. Try configuring JsonPath to use an other JsonProvider. This must be done before you access JsonPath the first time.

**Comment by denebchorny** [comment]
Sorry @kallestenflo, how do I have to do this? I am using gradle to use this library.

**Comment by jochenberger** [comment]
@kallestenflo this was fixed via #315.

**Comment by kallestenflo** [comment]
Fixed by #315
