### ISSUE TITLE
asserting empty object

### ISSUE THREAD

**Issue by adrian-herscu** [jayway/JsonPath#215]
With current (2.2.0) library I can do:

```
com.jayway.jsonassert.JsonAssert
                .with("6")
                .assertThat("$", org.hamcrest.Matchers.equalTo(6));
```

Now, what about asserting that a JSON object is empty, namely {} -- is it possible to write such an assertion?

```
com.jayway.jsonassert.JsonAssert
                .with("{}")
                .assertThat("$", ????);
```

**Comment by kallestenflo** [comment]
I think you will need to write a custom matcher.

**Comment by jochenberger** [comment]
See https://github.com/hamcrest/JavaHamcrest/issues/34, https://github.com/hamcrest/JavaHamcrest/issues/35.
@kallestenflo AFAICT, there's nothing left to do in JsonPath, so maybe we should close this.

**Comment by jochenberger** [comment]
Btw. you could use `with("{}").assertThat("$.size()", is(0));`
