### ISSUE TITLE
JsonPath#parse(URL) Is Treated Like JsonPath#parse(String)

### ISSUE THREAD

**Issue by ryanlevell** [jayway/JsonPath#218]
I updated from `1.2.0` to `2.2.0` and saw the issue below.
`JsonPath#parse(URL)` used to parse the URL's content. Now it parses the actual URL.
#### Java

``` java
// 1.2.0
System.out.println("1.2.0: " + JsonPath.parse(new URL("http://ip.jsontest.com/")).json());
// 2.2.0
System.out.println("2.2.0: " + JsonPath.parse(new URL("http://ip.jsontest.com/")).json());
```
#### Console

``` bash
1.2.0: {ip=192.168.1.1} # parses the content
2.2.0: http://ip.jsontest.com/ # parse the actual URL
```

**Comment by ryanlevell** [comment]
As a workaround, Apache Commons can be used to convert a web page's content to a string using a one-liner: `JsonPath.parse(org.apache.commons.io.IOUtils.toString(urlObject))`

**Comment by jlolling** [comment]
I generally do not think a URL is quite enough to get a content.
I suggest to remove this overloaded method JsonPath.parse(Url)

There are to many questions open.

Cheers
Jan

**Comment by pointwisefixed** [comment]
I agree with you @jlolling  There probably was a reason why URL stopped being used in the JsonContext and the HttpProvider (and Factory) were removed. Keeping them just creates inconsistent behavior like this issue.

**Comment by kallestenflo** [comment]
The API was actually broken. URL was accepted as input but was not handeled as one. It now works in simplest possible way but the method has been deprecated.
