### ISSUE TITLE
Relaxed Json parsing

### ISSUE THREAD

**Issue by frmz** [jayway/JsonPath#221]
It would be nice to be able to parse URLs like this without having to do anything:
http://finance.google.com/finance/info?q=NASDAQ%3aMSFT

So that's good JSON except for the first 2 chars, so it would be nice to have the parser able to find opening delimiter of JSON data and just forget about everything that goes after the last closing one

**Comment by jochenberger** [comment]
I think it's beyond the scope of this library to provide this behavior by default. You can always use a custom JsonProvider to parse data like that.

**Comment by kallestenflo** [comment]
We used to have support for this but removed it.
