### ISSUE TITLE
Methods to write

### ISSUE THREAD

**Issue by denebchorny** [jayway/JsonPath#223]
Hi sir,

does this library just work to retrieve data from a Json?

Is there any way to add data to json?

I mean, this is an json example:

``` json
{
     "_id":"",
     "name":"",
     "job":{
         "jobTitle":"",
         "places": ["","",""] 
     }
}
```

With this library I can access directly to the "places" property. If I modify it, how can I reflex this change back to the json?... Is it possible with this library or this is just for read properties?

Thanks in advance.

**Comment by denebchorny** [comment]
I think this is a very very estupid question if I read the first line in the library.

"A Java DSL for reading JSON documents."

Anyway I'll leave the question here. If the question is really dumb as I think you can close this entry

**Comment by warwickhunter** [comment]
Q: does this library just work to retrieve data from a Json?
A: Yes it does. You can use code or a Json Path expression like $.job.places to retrieve the places array

**Comment by rnc** [comment]
I am using it to (currently) delete / update parts of a JSON doc e.g.
```
DocumentContext doc = JsonPath.using( conf ).parse( jsonFile);
doc.set( "xpath-string", "update-value" );
```

**Comment by denebchorny** [comment]
Let me see if I understand correctly Mr. @rnc 

Using the initial example, this is the json I have:
```json
{
     "_id":"1",
     "name":"Peter",
     "job":{
         "jobTitle":"The 13th doctor",
         "places": ["Here","there","nowhere"] 
     }
}
```

1) If I want to retrieve/update de "places" array, have I to do something like this? 
2) how is the correct use of DocumentContext or where can I read about DocumentContext?

```java
String json = <the json I showed before>;
DocumentContext doc = JsonPath.parse(json);

// Retrieving the places
List<String> places = doc.read("job.places");

// Editing the places and putting back to the Doc
places.remove("there");
doc.set("job.places", places);

```
PD: The configuration I don't know how to use it yet, is it mandatory to use it?

I know there are a lot of questions and they could be dumb, but I'll be very glad of your help :D

Thanks in advance...

**Comment by rnc** [comment]
Configuration is not mandatory - there is a set of sensible defaults I believe. There is a google groups for this project which might be the best place to ask questions?

**Comment by denebchorny** [comment]
Thanks sir... You were very helpful

**Comment by chandankadannar** [comment]
how to add new object to json file using json path

**Comment by himanshushukla254** [comment]
not able to write by specifying the path and value using writeContext.
