### ISSUE TITLE
The dependency for json-path creates duplicate libraries of asm packages

### ISSUE THREAD

**Issue by tigerscar** [jayway/JsonPath#228]
The dependency for json-path (see below) causes after 'mvn eclipse:eclipse' two libraries with the asm packages (accessors-smart-1.1.jar and asm-5.0.3.jar). Both are providing the packages org.objectweb.asm and org.objectweb.asm.signature.

So it is impossible to make a runnable JAR file from Eclipse (but maybe I am unexperienced and there is a workaround for it, I don't know).

```
<dependency>
    <groupId>com.jayway.jsonpath</groupId>
    <artifactId>json-path</artifactId>
    <version>2.2.0</version>
</dependency>
```

A similar issue is posted in the issue management of json-smart-v2: https://github.com/netplex/json-smart-v2/issues/20

**Comment by kallestenflo** [comment]
Check out the comments here #224

**Comment by tigerscar** [comment]
Dear kallestenflo, thanks for the hint. I will try out to exclude it from my Maven pom.

        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
            <version>2.2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.ow2.asm</groupId>
                    <artifactId>asm</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by tigerscar** [comment]
The exclusion within the jsonpath dependency worked out for myself. 
You should definitely exclude this library from your build environment or update it to accessors-smart 1.1.

See https://github.com/netplex/json-smart-v2/issues/20.
