### ISSUE TITLE
How to express == null in a query

### ISSUE THREAD

**Issue by tabouzeid** [jayway/JsonPath#229]
I'd like to express be able to write a query where i can search for entries in a list which have a certain field unspecified. i.e. a null check on a field

[{"a":1, "c":2}{"c":2}]

I'd like to do something like this... not sure if it's possible with v2.2?
$.[?(@.c == 2 && (@.a == 2 || @.a == null))]

**Comment by mskonovalov** [comment]
you can use $.store.book[?(!@.isbn)]

**Comment by jochenberger** [comment]
@kallestenflo IMO this should be closed.
