### ISSUE TITLE
Failed to assert empty array

### ISSUE THREAD

**Issue by longtimeago** [jayway/JsonPath#232]
Trying to assert that an array is empty
```java
String json = "{ "arr": [] }";
MatcherAssert.assertThat(
        json,
        JsonPathMatchers.hasJsonPath("$.arr", Matchers.emptyArray())
);
```
and got 
```java
java.lang.AssertionError: 
Expected: has json path "$.arr" evaluated to an empty array
     but: json path "$['arr']" was evaluated to <[]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
```

Any ideas how to do the trick?

Thanks in advance

**Comment by helsing** [comment]
JSON arrays are represented as Lists in Java, so you should use Matchers.empty() instead of Matchers.emptyArray(). 

But I think you directed the attention to another bug:

    String json = "{ "arr": [] }";
    MatcherAssert.assertThat(json, hasJsonPath("$.arr"));

and got

    java.lang.AssertionError: 
    Expected: has json path "$.store.arr"
      but: json path "$['store']['arr']" was evaluated to <[]>

**Comment by longtimeago** [comment]
@helsing thank you very much for the hint. Indeed, it works with `Matchers.empty()`
And yes, your case failed. Looks like a bug?

**Comment by helsing** [comment]
@kallestenflo Wdyt? Would you like me to provide a fix? Or do you have some other suggestion?

**Comment by kallestenflo** [comment]
@helsing, a fix would be nice. FYI I'm reworking the internals (v 3.0) but the public API will hopefully stay intact.

**Comment by ozinal** [comment]
MockMvcResultMatchers.jsonPath("$.errorCodes", Matchers.empty());
