### ISSUE TITLE
Double brackets around array filtered by JsonPath.read

### ISSUE THREAD

**Issue by catshout** [jayway/JsonPath#233]
With a given JSON string

`{
    "CONFIGURATION": {
        "GLOBAL_PARAMETER": {
            "SOURCE": {
                "SYSTEM": "JMS",
                "APPLICATION": "SAP PI",
                "COMMUNICATION": {
                    "ADAPTER": "SAPEIB",
                    "PARAMETER": [{
                        "VALUE": "WBBDLD",
                        "NAME": "MESTYP"
                    },
                    {
                        "VALUE": "",
                        "NAME": "SNDPRN"
                    }]
                }
            }
        }
    }
}`

this statement

`String paramArr = JsonPath.read(headerJsonString, "$..PARAMETER").toString()`

produces a String

`[[{"NAME":"MESTYP","VALUE":"WBBDLD"},{"NAME":"SNDPRN","VALUE":""}]]`

with double brackets around, an array within an array.

**Comment by jochenberger** [comment]
That's expected. The outer array is the array that represents the results from your query. In this case, there is one result, represented by the inner array.
