### ISSUE TITLE
JsonPath failed to install on windows

### ISSUE THREAD

**Issue by pushpsmarty** [jayway/JsonPath#235]
I get below error logs:

$ npm update --save

> jsonpath@0.2.3 postinstall C:\Users\pushpkum\Desktop\IoT\dashboard\node_modules\jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\pushpkum\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "update" "--save"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! file C:\Windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.2\bin
npm ERR! path C:\Windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.2\bin
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.2\bin

npm ERR! jsonpath@0.2.3 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
npm ERR! spawn C:\Windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.2\bin ENOENT
npm ERR!
npm ERR! Failed at the jsonpath@0.2.3 postinstall script 'node lib/aesprim.js > generated/aesprim-browser.js'.
npm ERR! This is most likely a problem with the jsonpath package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/aesprim.js > generated/aesprim-browser.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jsonpath
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls jsonpath
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\pushpkum\Desktop\IoT\dashboard\npm-debug.log

I have below version of npm and node:
node: v4.4.4
npm: 2.15.1

Below are contents of my package.json:

{
  "name": "dashboard",
  "version": "1.0.0",
  "description": "Heat map dashboard",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "(git@10.78.163.69:IoT.git)"
  },
  "author": "Pranshi Sharma",
  "license": "Aricent",
  "dependencies": {
    "angular-resource": "^1.5.5",
    "body-parser": "^1.15.1",
    "d3": "^3.5.17",
    "ejs": "^2.4.1",
    "express": "^4.13.4",
    "jsonpath": "^0.2.3",
    "jsonschema": "^1.1.0",
    "mysql": "^2.10.2",
    "npm": "^3.9.3",
    "osprey": "^0.3.1",
    "raml-parser": "^0.8.17",
    "socket.io": "^1.4.6",
    "xml2js": "^0.4.16",
    "xmldom": "^0.1.22",
    "xpath": "0.0.23"
  }
}

**Comment by jochenberger** [comment]
This should be reported in https://github.com/dchester/jsonpath.
@kallestenflo I guess this can be closed.
