### ISSUE TITLE
Date for next release?

### ISSUE THREAD

**Issue by fhoeben** [jayway/JsonPath#239]
Do you have a plan when to do the next release? I would really like to use the new functionality to find keys when there value is `null`.

**Comment by burtonator** [comment]
It's December.. last release was in Feb?  

Another release is due I would say... Additionally. we a SEVERE bug (the ASM duplicate class related issue) which prevents this from being used anywhere near Elasticsearch and/or other major libraries.

**Comment by bosschaert** [comment]
+1
I think it would be great to have a new release. In my case I'm interested one that contains the fix for #207 and #209

**Comment by jochenberger** [comment]
@kallestenflo IMO this should be closed.

**Comment by pmouawad** [comment]
Hello @kallestenflo , 
I see lot of work currently on project, is a release planned soon ?
Thanks

**Comment by kallestenflo** [comment]
Hope to release first week in April if all goes well.
