### ISSUE TITLE
对数值型字段解析存在问题

### ISSUE THREAD

**Issue by javadevelopuser** [jayway/JsonPath#241]
json：{"base":{"pripid":"5001051201601191335376","regno":"500105008526483","entname":"重庆雷度文化传媒有限公司","enttypeno":"1152","enttype":"有限责任公司(法人独资)","estdate":"2016-02-16","lerep":"黄建国","regcap":1000.0,"dom":"重庆市江北区盘溪七支路11号7楼747号","opscope":"设计、制作、代理、发布国内外广告；礼仪服务；会议服务；展览展示服务；市场营销策划；承办经批准的文化艺术交流活动；企业形象策划；商务信息咨询；摄影服务。** [依法须经批准的项目，经相关部门批准后方可开展经营活动] ","opfrom":"2016-02-16","opto":"2033-06-30","regorgno":"500105","regorg":"重庆市工商行政管理局江北区分局","issblicdate":"2016-02-16","opstateno":"1","opstate":"存续（在营、开业、在册）","localorg":"500105","localadm":"500105020","idcard":"5BD6C21806F90CC176594684637934A9","apprdate":"2016-02-16","creditcode":"91500105MA5U4NGR0W"},"members":[{"oid":"5001051201602147146770","pripid":"5001051201601191335376","name":"黄建国","position":"执行董事、经理"},{"oid":"5001051201602147147112","pripid":"5001051201601191335376","name":"岳原","position":"监事"}],"brunchs":[],"accounts":[{"oid":"5001051201601191335376","pripid":"5001051201601191335376","ligprincipal":"林洋","liqmem":"黄建国,陈健"}],"investors":[{"oid":"5001051201602140752141","pripid":"5001051201601191335376","invtypeno":"2","invtype":"企业法人","inv":"辽宁雷度公共关系策划股份有限公司","blictypeno":"01","blictype":"公司执照","blicno":"912101000715095688","gInvaccon":[],"gInvsubcon":[]}],"alters":[],"ccjc":[],"illegals":[],"punishments":[],"stock":[],"motage":[],"gtjnz":[],"nzfz":[],"qyjy":[]}

**Comment by lishunt** [comment]
> json：{"base":{"pripid":"5001051201601191335376","regno":"500105008526483","entname":"重庆雷度文化传媒有限公司","enttypeno":"1152","enttype":"有限责任公司(法人独资)","estdate":"2016-02-16","lerep":"黄建国","regcap":1000.0,"dom":"重庆市江北区盘溪七支路11号7楼747号","opscope":"设计、制作、代理、发布国内外广告；礼仪服务；会议服务；展览展示服务；市场营销策划；承办经批准的文化艺术交流活动；企业形象策划；商务信息咨询；摄影服务。** [依法须经批准的项目，经相关部门批准后方可开展经营活动] ","opfrom":"2016-02-16","opto":"2033-06-30","regorgno":"500105","regorg":"重庆市工商行政管理局江北区分局","issblicdate":"2016-02-16","opstateno":"1","opstate":"存续（在营、开业、在册）","localorg":"500105","localadm":"500105020","idcard":"5BD6C21806F90CC176594684637934A9","apprdate":"2016-02-16","creditcode":"91500105MA5U4NGR0W"},"members":[{"oid":"5001051201602147146770","pripid":"5001051201601191335376","name":"黄建国","position":"执行董事、经理"},{"oid":"5001051201602147147112","pripid":"5001051201601191335376","name":"岳原","position":"监事"}],"brunchs":[],"accounts":[{"oid":"5001051201601191335376","pripid":"5001051201601191335376","ligprincipal":"林洋","liqmem":"黄建国,陈健"}],"investors":[{"oid":"5001051201602140752141","pripid":"5001051201601191335376","invtypeno":"2","invtype":"企业法人","inv":"辽宁雷度公共关系策划股份有限公司","blictypeno":"01","blictype":"公司执照","blicno":"912101000715095688","gInvaccon":[],"gInvsubcon":[]}],"alters":[],"ccjc":[],"illegals":[],"punishments":[],"stock":[],"motage":[],"gtjnz":[],"nzfz":[],"qyjy":[]}

怎么联系你？
