### ISSUE TITLE
Failed to extract an entry from an array generated by a filter

### ISSUE THREAD

**Issue by jmlamare** [jayway/JsonPath#243]
For Example

The following inputs generate no result
JSON: [{"a":1,"b":"X"},{"a":2,"b":"Y"},{"a":3,"b":"Z"}]
EXPR: $[?(@.a==1)][0]

**Comment by ghl3** [comment]
For a concrete example:

    JsonPath.read("[{\"x\":\"a\"}, {\"x\":\"b\"}]", "[?(@.x == 'a')]")

returns:

    [{x=a}]

but

    JsonPath.read("[{\"x\":\"a\"}, {\"x\":\"b\"}]", "[?(@.x == 'a')][0]")

returns

    []

We would expect it to return

  {"x"="a"}


This appears to happen when you do an index selection directly after a filter.

**Comment by lakshan93** [comment]
Are there any workaround to achieve this value?

**Comment by kallestenflo** [comment]
Duplicate of #272
