### ISSUE TITLE
Null in JSON, document outdated or bug

### ISSUE THREAD

**Issue by mohamnag** [jayway/JsonPath#245]
As stated on [this page](https://github.com/jayway/JsonPath/tree/master/json-path-assert) using any of these following assertions shall pass if the value of key `none` is `null` in JSON:

```java
assertThat(json, hasJsonPath("$.none"));
assertThat(json, isJson(withJsonPath("$.none")));
```

however using `json-path-assert` version 2.2.0 both of above will result in errors. It is also clear in source code that null is not accepted:
```java
    public static Matcher<? super Object> hasJsonPath(String jsonPath) {
        return describedAs("has json path %0",
                hasJsonPath(jsonPath, not(anyOf(nullValue(), empty()))),
                jsonPath);
    }
```

so is this a bug or a behaviour change? if behaviour change, what would be the best way to check if a key exists whether or not it is null.

**Comment by helsing** [comment]
This bug has been reported, fixed, and merged. See prev issues. However, the fix haven't been released yet.

**Comment by helsing** [comment]
Workaround using 2.2.0:

    assertThat(json, hasJsonPath("$.none", nullValue()));

or

    assertThat(json, hasJsonPath("$.none", anything()));

**Comment by mohamnag** [comment]
Sorry for duplicate, did a search but found nothing. Thanks for suggestions then will just close the ticket.
