### ISSUE TITLE
Update LICENSE please

### ISSUE THREAD

**Issue by attritionorg** [jayway/JsonPath#251]
https://github.com/jayway/JsonPath/blob/master/LICENSE

To apply the Apache License to your work, attach the following
boilerplate notice, with the fields enclosed by brackets "[]"
replaced with your own identifying information.

LICENSE file currently reads:

Copyright [yyyy] [name of copyright owner]

**Comment by asbachb** [comment]
I don't think that's necessary since this is just an example howto the license information per file should look like.

**Comment by kallestenflo** [comment]
Added "2017 Jayway" to copyright.
