### ISSUE TITLE
Can I test entire json file with JsonPath?

### ISSUE THREAD

**Issue by ramswaroop** [jayway/JsonPath#255]
Suppose I have a json file named `test.json` and I want to assert like this:

``` java
String response = service.getResponse();
assertTrue(JsonPath.equals(response, "path-to/test.json"));
```

Is there a way to do so currently?

**Comment by helsing** [comment]
I understand what you want: you are more or less comparing a json payload with another json? But there's nothing "json-pathy" about the problem, i.e there is no need to use json-path features to solve it. Right?

**Comment by ramswaroop** [comment]
Hmm... I am not quite sure. Maybe you can help. Suppose you receive a payload like:
```json
{
    "name" : "ram",
    "age": 28
}
```
and you have a json file with which you're asserting like:
```json
{
    "age": 28,
    "name" : "ram"
}
```
So, how do you make sure that the assert works just fine? Hope you get what I am trying to say here.

**Comment by helsing** [comment]
If you want to do exact matching, e.g comparing the full payload with a full identical json, I would parse it into a Map/List structure, using e.g jackson-library ObjectMapper (new ObjectMapper().readValue(myJsonString, Map.class). Then you do the same with the expected payload. Now you have two Map/List structures, each representing the json structure. You could assert using regular hamcrest, e.g something along these lines:

    Map<String, Object> actual = new ObjectMapper().readValue(actualJsonString, Map.class);
    Map<String, Object> expected = new ObjectMapper().readValue(expectedJsonString, Map.class);
    assertThat(actual, equalTo(expected));

If you want to use more fuzzy matching, you could use json-path-assert library, e.g:

    assertThat(actualJsonString, hasJsonPath("name", equalTo("ram"));
    assertThat(actualJsonString, hasJsonPath("age", equalTo(28));

This wouldn't fail on any superfluous elements in the json, though, so you need to ask yourself if that's what you want to achieve?

**Comment by mohamnag** [comment]
I found this because I have a very similar case, however the equality does not apply in the sense of whole object AND values but rather I want to make sure the actual object has all the keys and similar structure of the expected object.

is there a way to do this with JsonPath's hamcrest assertions?

**Comment by helsing** [comment]
Could you provide more information on what it is you want to verify?

**Comment by mohamnag** [comment]
In other words I want to check the structure (and not the values) of two json strings to match, both of which are potentially generated on the fly so the keys could not be hard coded in a `hasJsonPath` style.

for example this:
```
{
    "name" : "ram",
    "age": 28
}
```
has same structure as:
```
{
    "name" : "cpu",
    "age": 10
}
```

even if values do not match. It is also possible to have sub-objects and so on that all should be taken into account.
