### ISSUE TITLE
SUPPRESS_EXCEPTIONS does not suppress exceptions ...

### ISSUE THREAD

**Issue by supertick** [jayway/JsonPath#259]
First .. thanks for this great library ..

I'm trying to get a null returned without throwing 
When "messages" attribute in a json document is missing, the following code throws

```
        Configuration conf = Configuration.defaultConfiguration();
        // conf.addOptions(Option.DEFAULT_PATH_LEAF_TO_NULL);
        conf.addOptions(Option.ALWAYS_RETURN_LIST);
        conf.addOptions(Option.SUPPRESS_EXCEPTIONS);
        messages = JsonPath.using(conf).parse(json).read("$.messages");
```

I've tried every permutation - but it always seems to throw .. 
Any guidance would be appreciated, thanks.

**Comment by pgoldweic** [comment]
Did you try creating a new configuration as follows?
Configuration.builder().options(Option.ALWAYS_RETURN_LIST, Option.SUPPRESS_EXCEPTIONS).build();

I believe I had to do this in order to get this option to work for me in the past.

**Comment by kallestenflo** [comment]
The configuration is imutable. Try this:  

Configuration conf = Configuration.defaultConfiguration()
    .addOptions(Option.ALWAYS_RETURN_LIST)
    .addOptions(Option.SUPPRESS_EXCEPTIONS);

**Comment by pgoldweic** [comment]
The solution I provided above also works, right? Or, did something change in the latest versions of this tool?

**Comment by kallestenflo** [comment]
Yes it works fine.

**Comment by leceal** [comment]
Also, you could use this form:

Configuration conf = Configuration.defaultConfiguration().setOptions(Option.ALWAYS_RETURN_LIST, Option.SUPPRESS_EXCEPTIONS);
