### ISSUE TITLE
JacksonJsonNodeJsonProvider   is not returning reference but a copy of the JsonNode  

### ISSUE THREAD

**Issue by ahmedrehman** [jayway/JsonPath#264]
When you have a json document as JsonNode  and you use json path to find  node a.b.Mynode  you dont get that node but a copy of it.  
So if you change values in the node Mynode  it does not change the original document.so you cant use it to modify the JsonNode document.   

the bug seems to be in  JacksonJsonNodeJsonProvider
private JsonNode createJsonElement(Object o) {
        if(o instanceof JsonNode)return (JsonNode)o; // Please this !!!
         return objectMapper.valueToTree(o);  // this kills the reference it makes a copy
}

**Comment by jlolling** [comment]
This is a bug which is actually long ago solved in 2.2.1. Are you running the latest release?

**Comment by jlolling** [comment]
Can we close this issue? Do you have found your problem @ahmedrehman ?
