### ISSUE TITLE
simple JSONArray search using JsonPath

### ISSUE THREAD

**Issue by zishanj** [jayway/JsonPath#265]
Here is a sample JSONArray in which I am trying to search:

`["ح م د","ر ب ب","ع ل م","ر ح م","م ل ک","ی و م","د ی ن","ع ب د","ع ون","ع ون","س ف ہ","س ف ہ"]`

I am trying to search array with first character "س" using following XPath expression which is returning 0 instead of 2:

`JsonPath.read(myJSONArray.toString(), "$[*][?(@ =~ /^س/i)]")`

My array is of Arabic characters, so its in RTL and I am trying to use ^ in regex to find first character but its returning 0, if I omit ^, still its returning 0. Any idea whats going wrong?

**Comment by kallestenflo** [comment]
Have you tried with out Arabic RTL?

**Comment by zishanj** [comment]
Yes, just checked and it doesn't work with that too. Probably some problem with XPath expression?

**Comment by zishanj** [comment]
I did further test and it seems that XPath only works with JSONObjects type Array, for simple JSONArray like above the XPath regex doesn't work. It will works with `$[*]` which displays entire list.

**Comment by kallestenflo** [comment]
You must match the whole word not only first char.

```
String json = "[\"abc\",\"def\"]";

Assertions.assertThat(
  JsonPath.read(json, "$[?(@ =~ /^a.*/i)]").equals(Collections.singletonList("abc"))
);
```
