### ISSUE TITLE
'Options' :  Can't resolved the method addOptions(?),and import has made

### ISSUE THREAD

**Issue by lol666666** [jayway/JsonPath#266]
## When i start the intellij IDE,the error always shows:

<img width="848" alt="2016-09-30 6 25 14" src="https://cloud.githubusercontent.com/assets/10813359/18988858/489705de-873b-11e6-9397-6ef09118c56f.png">

**when i step into the error method,code as follows:**

```
   package com.jayway.jsonpath;
    public enum Option {
    THROW_ON_MISSING_PROPERTY;
    private Option() {
    }
}
```

**But i refresh the project build.gradle file,the error is disappear.
the com.jayway.jsonpath.option change the normal status:**

```
package com.jayway.jsonpath;

public enum Option {
    DEFAULT_PATH_LEAF_TO_NULL,
    ALWAYS_RETURN_LIST,
    AS_PATH_LIST,
    SUPPRESS_EXCEPTIONS,
    REQUIRE_PROPERTIES;

    private Option() {
    }
}
```

**I'm so confused,what's the problem?**

please help me,very thanks.

**Comment by kallestenflo** [comment]
Can't see this is is a JsonPath issue.
