### ISSUE TITLE
Can't use single quotes with Jackson, "in" predicate operator

### ISSUE THREAD

**Issue by johnflavin** [jayway/JsonPath#275]
The README says, in [section Filter Operators](https://github.com/jayway/JsonPath#filter-operators)

> String literals must be enclosed by single or double quotes (`[?(@.color == 'blue')]` or `[?(@.color == "blue")]`).

When using a `JacksonJsonProvider` or `JacksonJsonNodeJsonProvider`, and when testing a predicate with the `in` operator, an `InvalidJsonException` is thrown.

I've uploaded a test class to a gist: https://gist.github.com/johnflavin/31aea6ac790f32cbbb528124eceeb4df. In it, I try out all the different json provider classes, with single and double quotes, in predicates using `?(@.foo == 'bar')` and `?(@.foo in ['bar'])`. Everything works as expected, except for Jackson providers, single quotes, and `in`.

**Comment by chb0github** [comment]
Use `"` double quotes

`$.properties[?(@.name ==\ "driverContactId\").value`

works for me

**Comment by johnflavin** [comment]
I think you missed the point of the issue. I know that double quotes work. I know that `==` works. I provided a test class that tests this case and shows that it passes. 

The only thing I am saying does not work is a predicate with a `JacksonMappingProvider`, using single quotes, and the `in` operator.

**Comment by kallestenflo** [comment]
Works as expected.
