### ISSUE TITLE
JsonPath.compile("$.[state,city]") fails with InvalidPathException

### ISSUE THREAD

**Issue by pmouawad** [jayway/JsonPath#278]
Hello,
When calling:
`JsonPath.compile("$.[state,city]")`
I get exception:
`com.jayway.jsonpath.InvalidPathException: Could not parse token starting at position 2. Expected ?, ', 0-9, * `

As far as I understand this is ok as per http://goessner.net/articles/JsonPath/:

[,] 	Union operator in XPath results in a combination of node sets. JSONPath allows alternate names or array indices as a set. 

Thanks

**Comment by pmouawad** [comment]
You can test on http://jsonpath.com/ if you want

**Comment by pmouawad** [comment]
You can use this JSON code to test:

`{   "employees": [     {       "firstName": "John",       "lastName": "Doe"     },     {       "firstName": "Anna",       "lastName": "Smith"     },     {       "firstName": "Peter",       "lastName": "Jones"     }   ],   "city": "Castle Rock",   "state": "Maine" }`

**Comment by ra0077** [comment]
Hi,

If you test it with http://jsonpath.com/ it's ok

But if you test it with https://jsonpath.curiousconcept.com/ and JSONPath 0.3.4 implementation it's failed (JSONPath Error: Unable to parse token state,city in expression: .[state,city].). But with JSONPath 0.8.3

Antonio

**Comment by tjakopanec** [comment]
This one should work: $.['state','city']

**Comment by kallestenflo** [comment]
The query should be $.['state','city']. 

There is currently a bug in JsonPath. Given the sample JSON above it should return:

['Castle Rock', 'Maine']

**Comment by pmouawad** [comment]
Thanks for answer !

**Comment by AkashItorix** [comment]
When I try to parse a swagger using the path $..[description,title] I'm getting Invalid Path Exception.But I'm able to get the response in when I try to evaluate the same in jsonpath.com
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/105375362/215075807-053bbe4f-6737-4f96-8a16-52e7b6934caf.png">
Used petstore swagger for testing
