### ISSUE TITLE
Receiving app:transformClassesWithDexForDebug error on ver 2.2.0

### ISSUE THREAD

**Issue by zishanj** [jayway/JsonPath#281]
I am receiving this error on version 2.2.0 while Building APK:

> Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lorg/objectweb/asm/AnnotationVisitor;

The only workaround is to enable MultiDex. Any help please?

**Comment by zishanj** [comment]
solved it by excluding ASM:

`compile ('com.jayway.jsonpath:json-path:2.2.0') { exclude group: 'org.ow2.asm' }`

**Comment by zishanj** [comment]
no need to for `multiDexEnabled true` after this.

**Comment by andruwik777** [comment]
Cool, thanks for solution!
