### ISSUE TITLE
How to handle JSON with namespaces

### ISSUE THREAD

**Issue by kmandeville** [jayway/JsonPath#284]
I'm having trouble using JsonPath for checking json with namespaces in front of fields. I haven't been able to find anything from google or looking through existing issues or the documentation. I haven't been able to get anything to work. I have the following snippet of json: 

```
{
  "_embedded" : {
    "bb:list" : [ {
      "id" : "id",
      "label" : "label",
      "description" : "description",
      "timezone" : "timezone",
      "postalAddress" : {
        "addressCountry" : "country",
        "addressLocality" : "city",
        "addressRegion" : "state",
        "postalCode" : "postal code",
        "streetAddress" : "street address"
      }
    } ]
  }
}
```
And I'm trying to check the bb:list field to see how many items are in it. This JsonPath expression does not seem to work: 

"$._embedded.bb:list"

If I remove the "bb:" then using this works   "$._embedded.list" so it's the bb: that it doesn't seem to like.

**Comment by tjakopanec** [comment]
Try this `$._embedded.['bb:list']`, although this one `$._embedded.bb:list` also works for me.
You can try it online here: http://jsonpath.herokuapp.com/

**Comment by kmandeville** [comment]
Thanks. It turns out the problem is not with the JsonPath expression, or JsonPath at all. SpringBoot was bringing in JsonPath so it all compiled, but it seemed that at runtime, it just wasn't working for whatever reason. I explicitly added JsonPath to my dependency list and it magically started working without the brackets.
