### ISSUE TITLE
When using == 1 is equal to '1'

### ISSUE THREAD

**Issue by AlixBa** [jayway/JsonPath#288]
http://jsonpath.herokuapp.com/?path=$..book[?(@.price%20==%20'8.95')]

But the readme says the opposite, is that a bug? Shouldn't we get anything in the page above?

**Comment by jochenberger** [comment]
See also #145

**Comment by AlixBa** [comment]
ho yeah I forgot to update.
The readme should be updated to specify that the correct operator for this kind of op is === not ==.
