### ISSUE TITLE
Incorrect behavior when used with JacksonJsonNodeJsonProvider

### ISSUE THREAD

**Issue by kgignatyev** [jayway/JsonPath#290]
[jsonpathwithjackson.zip](https://github.com/jayway/JsonPath/files/674754/jsonpathwithjackson.zip)

When JsonPath is configured with JacksonJsonNodeJsonProvider and used against given JsonNode it does not unwrap value and causes class cast exception
  String principalId = JsonPath.read(jsonNode, "$.userIdentity.principalId"); causes 

java.lang.ClassCastException: com.fasterxml.jackson.databind.node.TextNode cannot be cast to java.lang.String

Please have look at full repro case project attached:  testJsonPathValueRead() method

com.jayway.jsonpath.Configuration.setDefaults(new com.jayway.jsonpath.Configuration.Defaults() {

            private final JsonProvider jsonProvider = new JacksonJsonNodeJsonProvider();
            private final MappingProvider mappingProvider = new JacksonMappingProvider();
            public JsonProvider jsonProvider() {
                return jsonProvider;
            }
            public MappingProvider mappingProvider() {
                return mappingProvider;
            }
            public Set<Option> options() {
                return EnumSet.noneOf(Option.class);
            }
        });

**Comment by jochenberger** [comment]
I may be wrong but I think that you should be using `JacksonJsonProvider` instead of `JacksonJsonNodeJsonProvider`.

**Comment by kallestenflo** [comment]
The types of the underlying JsonProvider are returned if a type is not provided.

```java
    @Test
    public void strings_are_unwrapped() {
        JsonNode node = using(JACKSON_JSON_NODE_CONFIGURATION)
                        .parse(JSON_DOCUMENT).read("$.string-property");
        String unwrapped = using(JACKSON_JSON_NODE_CONFIGURATION)
                        .parse(JSON_DOCUMENT).read("$.string-property", String.class);

        assertThat(unwrapped).isEqualTo("string-value");
        assertThat(unwrapped).isEqualTo(node.asText());
    }
```

**Comment by kgignatyev** [comment]
Even if I am using JacksonJsonProvider the behavior is **_inconsistent_**  with 'default' settings, that is the point. 
Default reads string fine 
 JsonPath.read(JsonPathDirect.class.getResourceAsStream("/test.json"),"$.userIdentity.principalId");
and if provider is set to Jackson the code above then the code starts to fail.
