### ISSUE TITLE
Invalid and incomplete JSON returned

### ISSUE THREAD

**Issue by ammar-khan** [jayway/JsonPath#292]
JSON Used:
{"store":{"book":{"category":"reference","author":"Nigel Rees","title":"Sayings of the Century","price":8.95}},"expensive":10}

JSON Path: $.store.book

Returned JSON:
{author=NigelRees, price=8.95, category=reference, title=SayingsoftheCentury}

(invalid JSON without quotes, spaces between values truncated, node missing)

**Comment by cinterloper** [comment]
I also have experienced this issue

**Comment by plastic-karma** [comment]
Can you provide a code snippet how you use the path expression and the used JSON. The following code works for me:

```
import com.fasterxml.jackson.databind.JsonNode;
import com.jayway.jsonpath.spi.json.JacksonJsonNodeJsonProvider;
import com.jayway.jsonpath.spi.mapper.JacksonMappingProvider;

//...
final String json = "{\"store\":{\"book\":{\"category\":\"reference\",\"author\":\"Nigel Rees\",\"title\":\"Sayings of the Century\",\"price\":8.95}},\"expensive\":10}";
final Object read = 
    JsonPath.using(
            Configuration
                    .builder()
                    .mappingProvider(new JacksonMappingProvider())
                    .jsonProvider(new JacksonJsonNodeJsonProvider())
                    .build()
    ).parse(json).read("$.store.book",  JsonNode.class);
System.out.println(read);
// prints: {"category":"reference","author":"Nigel Rees","title":"Sayings of the Century","price":8.95}
//...
```

**Comment by jochenberger** [comment]
@kallestenflo IMO this should be closed until someone provides instructions how to reproduce the issue.

**Comment by kallestenflo** [comment]
Can not reproduce.
