### ISSUE TITLE
Regex is not working

### ISSUE THREAD

**Issue by ankitgupshup** [jayway/JsonPath#296]
I'm using this regex. But it's not working. $..book[?(@.author=~/\bRees\b/i)]

**Comment by jochenberger** [comment]
See http://jsonpath.herokuapp.com/?path=$.store..[2].author
The Goessner implementation also behaves funny.

**Comment by jochenberger** [comment]
The behavior is correct, `=~` means regex *match*, not regex *find*. You probably want to use `$..book[?(@.author=~/\b.*Rees\b/i)]`.
@kallestenflo I guess, this can be closed.

**Comment by kallestenflo** [comment]
Works as expected.
