### ISSUE TITLE
Next Maven Release Date

### ISSUE THREAD

**Issue by tabouzeid** [jayway/JsonPath#298]
when is it?

**Comment by jlolling** [comment]
Yes, exactly also my question. I am working currently with selfmade snapshots in my own repo.

**Comment by sgliech** [comment]
We would also appreciate a new release to get the "optional tapestry5" fix live!

We are currently having problems to activate JsonPath in our OSGi containers because of this which blocks a big update for our AWS SDK dependency.

**Comment by shorea** [comment]
+1, the SDK can work around it by making json-path optional but would prefer the tapestry fix

**Comment by shorea** [comment]
Just curious if a release will happen soon. Any update on when Maven will be updated?

**Comment by jochenberger** [comment]
@kallestenflo IMO this should be closed.

**Comment by kallestenflo** [comment]
Working on it.
