### ISSUE TITLE
Need case insensitive path option

### ISSUE THREAD

**Issue by jaffadog** [jayway/JsonPath#301]
See http://stackoverflow.com/questions/42057597/case-insensitive-jsonpath-expression for use case.

Current feature state supports using regex filter expressions (including case-insensitivity) to evaluate property vales, but we don't have a way of specifying case-insensitive path/property names.

**Comment by jlolling** [comment]
I guess the problem here is, the actual gathering of the attribute is done by the underlying frameworks and they must support this feature - I fear this is not the case.
This feature would require to inspect the object first before start finding the attribute.

**Comment by kallestenflo** [comment]
Agree with @jlolling. This is not supported by underlying JSON libs and would require a lot of changes.
