### ISSUE TITLE
Difference between json-path-2.2.0.jar and json-path-1.2.0.jar with respect to wildcard in json expression

### ISSUE THREAD

**Issue by RadhaR4** [jayway/JsonPath#303]
For the below json message,
{  
   "one":{  
      "number":1
   },
   "two":{  
      "number":2
   }
}
When trying below json path expression,
   $.*.number  --> is treated as String in json-path-1.2.0.jar
   $.*.number --> is treated as array  in json-path-2.2.0.jar

Is this because of the difference in jar file version?I could not get details from Release notes.Please advice.

**Comment by jlolling** [comment]
It works correctly in jayway 2.2 ! The result as String is wrong.

**Comment by RadhaR4** [comment]
Thankyou @jlolling ... So, its confirmed that jsonpath 1.2.0 had this as a bug

**Comment by jochenberger** [comment]
@kallestenflo I guess we can close this then
