### ISSUE TITLE
Facing issue with Array filters when using multi-level value as filter condition

### ISSUE THREAD

**Issue by susnigdha1** [jayway/JsonPath#307]
Refer below mentioned JSON for example:
{
	"myJsonRootArray": [{
		"sampleData": "xyz",
		"myJssonChildArray": [{
			"item": "Hello",
			"text": {
				"greetings": "How are you?",
				"salutation": "MR"
			}
		}]
	}, {
		"sampleData": "abc",
		"myJssonChildArray": [{
			"item": "Bye",
			"text": {
				"greetings": "Good bye, see you soon",
				"salutation": "MS"
			}
		}]
	}]
}
I am trying to apply below filter to myJsonChildArray, which results in Error. I am not able to rectify this error and it seems like a limitation of JsonPath. 
$.myJsonRootArray[0].myJssonChildArray[?(@.text.salutation=='MR')]
Please let me know if multi-level data filters work for JsonPath - Arrays.

**Comment by kallestenflo** [comment]
You have an error in your path. Remove trailing 1 in myJssonChildArray.

Try it out here http://jsonpath.herokuapp.com <http://jsonpath.herokuapp.com/>

**Comment by jochenberger** [comment]
@kallestenflo As this was apparently an error in the data, we should close this.
