### ISSUE TITLE
JacksonJsonNodeJsonProvider.createJsonElement() clones JsonNodes

### ISSUE THREAD

**Issue by clementpellerin** [jayway/JsonPath#308]
When using Jackson JsonNodes, JsonPath returns cloned nodes instead of nodes found in the tree. That's because JacksonJsonNodeJsonProvider.createJsonElement() clones JsonNodes instead of casting them.

**Comment by jlolling** [comment]
This bug is a duplicate from bug 211 and is already solved.

**Comment by clementpellerin** [comment]
Oh well. I looked carefully against open bugs and obviously did not find it.
Next time I'll check against the trunk instead of the latest release.
