### ISSUE TITLE
is this jsonpath same to rest-assured's json-path?

### ISSUE THREAD

**Issue by fox4it** [jayway/JsonPath#326]
is this jsonpath same to rest-assured's json-path?

if different, can you tell me the focus each other

thanks

**Comment by kallestenflo** [comment]
No it's not. This implementation aims to be compliant with the JsonPath specs as defined by Stefan Goessner http://goessner.net/articles/JsonPath/index.html#e2. The RestAssured implementation has an unfortunate name and is a wrapper around the Groovy JsonSlurper and does not strive to implement JsonPath.
