### ISSUE TITLE
Main doc page doesn't document TypeRef usage

### ISSUE THREAD

**Issue by davidmichaelkarr** [jayway/JsonPath#333]
I only started looking at JsonPath a couple of days ago, to try to improve some code that's using it. I posted a SO question about it (http://stackoverflow.com/questions/42986914/strategies-for-iterating-through-jsonpath-array), and someone gave me a good answer, using the "`TypeRef`" class. It appears that this is like specifying a Class object, but it communicates generic type info. I noticed that the main doc page for JsonPath doesn't even mention this. This should be documented there.

**Comment by kallestenflo** [comment]
Added new section to documentation.
