### ISSUE TITLE
InvalidPathException on last index pattern [@.length -1]

### ISSUE THREAD

**Issue by olajuwon99** [jayway/JsonPath#338]
In version 2.0.0 this worked (`contextSize`). But for the current 2.2.0 it's a regression, In `PathCompiler::readNextToken` there is no support for it.

**Comment by kallestenflo** [comment]
Could you provide a example?

**Comment by jochenberger** [comment]
@olajuwon99 Please search for existing issues before creating new ones.

**Comment by jochenberger** [comment]
@kallestenflo Dupe of #198

**Comment by olajuwon99** [comment]
Thanks for the quick reply!
> In the upcoming version, you'll be able to use negative array indexes, i.e. $.store.book[-1].title to get the last book's title.

> 

Unfortunately I can't tell that to my customers. Will wait with the version bump until a more complete fix is available.
