### ISSUE TITLE
read methods with JsonPath parameter missing

### ISSUE THREAD

**Issue by szavrel** [jayway/JsonPath#72]
Hi!

First of all thanks for the great library! I've noticed that there seem to be some features missing from the release compared to the documentation in the readme. According to the readme doc:

*All  read  operations are overloaded and also supports compiled JsonPath objects. This can be useful from a performance perspective if the same path is to be executed many times.

`JsonPath compiledPath = JsonPath.compile("$.store.book[1].author");

String author2 = JsonPath.read(document, compiledPath);`*

I've worked with release 1.2.0 and now 2.0.0 and those operations do not exists. Am I missing something? Do I need additional libraries? Otherwise I'd suggest to remove this part from the docs or mark as not yet supported.

Thanks Stephan

**Comment by kallestenflo** [comment]
Thank you! I will update the documentation.

**Comment by kallestenflo** [comment]
Invalid documentation removed,
