### ISSUE TITLE
read operations missing class parameter

### ISSUE THREAD

**Issue by szavrel** [jayway/JsonPath#73]
Hi!

Similar to issue #72, the readme doc uses calls like:

*Date date = JsonPath.parse(json).read("$['date_as_long']", Date.class);*

Seems like those operations are not part of the released artifacts. Tested with release 1.2.0 and 2.0.0.

Greets
Stephan

**Comment by kallestenflo** [comment]
Doc verified against 2.0.0
```java
    @Test
    public void issue_github_73() {
        String json = "{\"date_as_long\" : 1427301546752}";

        Date expectedDate = new Date(1427301546752L);

        Date mappedDate = JsonPath.parse(json).read("$['date_as_long']", Date.class);

        Assertions.assertThat(expectedDate).isEqualTo(mappedDate);
    }
```
