### ISSUE TITLE
queries to large json objects fail to return a result. 

### ISSUE THREAD

**Issue by jeremyjjbrown** [jayway/JsonPath#76]
I have a fairly large json object that fails to return results. It passes http://jsonlint.com/

http://pastebin.com/BBb2B2BY

Running even simple queries has failed to return consistent results in both my code and https://jsonpath.herokuapp.com. 

For example:
 $.frameworks returns nothing
$.frameworks[?(@.id == '20150127-110351-1513192458-5050-8587-0000')] returns the entire object in java and nothing online.
$.frameworks[?(@.hostname =~ /.*cloud.in.here.com/)] returns the correct result in java and nothing online.

I am using JsonPath 2.0.0 and java version "1.7.0_67"

**Comment by kallestenflo** [comment]
This was an issue in son-smart. I have created an issue https://code.google.com/p/json-smart/issues/detail?id=55. 

Configure JsonPath to use an other JsonProvider when you bootstrap your application

```java
Configuration.setDefaults(new Configuration.Defaults() {
            @Override
            public JsonProvider jsonProvider() {
                return new JacksonJsonProvider();
            }

            @Override
            public Set<Option> options() {
                return EnumSet.noneOf(Option.class);
            }

            @Override
            public MappingProvider mappingProvider() {
                return new JacksonMappingProvider();
            }
        });
```

Don't forget to add Jackson to your classpath
```xml
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.4.5</version>
</dependency> 
```

**Comment by jeremyjjbrown** [comment]
Thanks! Jackson is working.

For the record I had addressed the BigDecimal Error with this code.

```java
       JSONValue.defaultWriter.registerWriter(new JsonWriterI<Object>() {
            public void writeJSONString(Object value, Appendable out, JSONStyle compression) throws IOException {
                out.append(value.toString());
           }
        }, BigDecimal.class);
```
I never got the deserialization Error once I registered the handler. It just returned bad results. Maybe you guys want to switch back to Jackson for default?

**Comment by pcdingman** [comment]
I was able to get around the BigDecimal error by turning off the high precision numeric support in json-smart by creating my own json-smart configuration.

	public static final Configuration JSON_SMART_CONFIGURATION = Configuration
			.builder()
			.mappingProvider(new JsonSmartMappingProvider())
			.jsonProvider(new JsonSmartJsonProvider(JSONParser.MODE_PERMISSIVE ^ JSONParser.USE_HI_PRECISION_FLOAT))
			.build();
