### ISSUE TITLE
How to deal with Optional Paths answer 

### ISSUE THREAD

**Issue by avaz** [jayway/JsonPath#78]
Hi,

Sorry if this is answered is somewhere else but I can't find the solution.
I'm consuming a service that sends back a json with fields that are optional, they can be returned or not with regarding of the query that I send to it. How I deal with this situation?
Example:
```json
{[
{
"id": "1",
"name": "Test",
"location": {"address": "Street 1", "crossStreet": "Street 2"}
},
{
"id": "1",
"name": "Test",
"location": {"address": "Street 1"}
}
]} 
```
The `crossStreet` field is optional, how I define optional fields in jsonpath? Because, on my code, when I use `$.location.crossStreet` I get an `com.jayway.jsonpath.PathNotFoundException: No results for path: $['location']['crossStreet']` exception. How can I avoid the exception?

Thanks.

**Comment by kallestenflo** [comment]
Please ask questions at the google group https://groups.google.com/forum/#!forum/jsonpath

Your JSON is not valid. I will answer based on the JSON below

```javascript
[
    {
        "id": "1",
        "name": "Test",
        "location": {
            "address": "Street 1",
            "crossStreet": "Street 2"
        }
    },
    {
        "id": "1",
        "name": "Test",
        "location": {
            "address": "Street 1"
        }
    }
]
```

The default configuration will return 

```java
List<String> crossStreets = JsonPath.parse(json).read("$[*].location.crossStreet");
Assertions.assertThat(crossStreets).containsExactly("Street 2");
```

If you want results from `location` objects that does not define `crossStreet ` you must tweak the configuration

```java
Configuration conf = Configuration.defaultConfiguration()
   .addOptions(Option.DEFAULT_PATH_LEAF_TO_NULL);

List<String> crossStreets = JsonPath.using(conf)
   .parse(json)
   .read("$[*].location.crossStreet");
Assertions.assertThat(crossStreets).containsExactly("Street 2", null);
``` 

If this is your preferred default behaviour you can configure this when you bootstrap your application.

```java
Configuration.setDefaults(new Configuration.Defaults() {
    private final Set<Option> options = EnumSet.of(Option.DEFAULT_PATH_LEAF_TO_NULL);

    @Override
    public JsonProvider jsonProvider() {
        return new JsonSmartJsonProvider(); //json-smart is not thread safe
    }

    @Override
    public Set<Option> options() {
        return options;
    }

    @Override
    public MappingProvider mappingProvider() {
        return new JsonSmartMappingProvider();
    }
});
```

Hope this answers your question.

**Comment by avaz** [comment]
Hi @kallestenflo, thanks for reply.

I already have tried your suggestion and it's not working too. 
I've posted a more completed question in GoogleGroups: https://groups.google.com/forum/#!topic/jsonpath/yPurMLMbB2Y

If you can see there I will be glad.

Thanks for your attention.

Regards.

**Comment by manusan** [comment]
For some reason, tweaking configuration on documentation [(tweaking-configuration)](https://github.com/jayway/JsonPath/tree/production#tweaking-configuration) does not work as expected, use this:
`Configuration conf = Configuration.builder().options(Option.DEFAULT_PATH_LEAF_TO_NULL).build();`
