### ISSUE TITLE
Make use of org.json

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [jayway/JsonPath#80]
Hi,
I just strumbled upon this library so don't blame me if I didn't see anything obvious.
I'm just wondering why the library has no interface to the popular classes of org.json.*.

Have a nice day
Hubert Grzeskowiak

**Comment by kallestenflo** [comment]
Hi,
you are actually the first to ask about org.json support. I think it will be similar to the GsonProvider. Feel free to have a look. :-)

**Comment by stleary** [comment]
Thanks, I am interested in a JsonProvider for JSON-Java unit testing, so will have a look.

**Comment by kallestenflo** [comment]
I have actually started to implement this feature. Not sure when it will be ready but it's in the pipe.

**Comment by stleary** [comment]
Great, let me know if there is anything I can do to assist.

**Comment by kallestenflo** [comment]
A JsonOrgJsonProvider is part of 2.1 release.

**Comment by hubertgrzeskowiak** [comment]
Nice, thanks!
