### ISSUE TITLE
Reading an object does not maintain attribute order and is limited to 130 attributes 

### ISSUE THREAD

**Issue by javierpajaro** [jayway/JsonPath#82]
Hi All,

Reading an object  using JsonPath.read(String json, ....) does not maintain attribute order and is limited to 130 attributes.

Is there any way to handle this via configuration?

Thanks, Javier.

**Comment by kallestenflo** [comment]
What version are you using?

**Comment by javierpajaro** [comment]
I fixed it changing the provider to gson. 

Thanks.

**Comment by javierpajaro** [comment]
Hi,

json-smart guys answered https://github.com/netplex/json-smart-v2/issues/14

So, I will try extending JSONObject  from LinkedHashMap.

**Comment by kallestenflo** [comment]
JsonSmartProvider now defaults to JSONValue.defaultReader.DEFAULT_ORDERED using LinkedHashMap for representing JSON objects.
