### ISSUE TITLE
Odd path read error

### ISSUE THREAD

**Issue by croteb** [jayway/JsonPath#84]
I have a very simple project that I generated with mvn:
mvn -B archetype:generate   -DarchetypeGroupId=org.apache.maven.archetypes   -DgroupId=com.mycompany.app   -DartifactId=my-app

I then updated with a simple pom.xml and updated the AppTest.java with:

        try {

                JsonPath path2 = JsonPath.compile( "$.userName" );

                ReadContext ctx = JsonPath.parse("{\"userName\":\"tstark\"}");

                path2.read(ctx);

                assertTrue(true);

                System.out.println("SUCCESS");

        } catch(Exception e){

                e.printStackTrace();

                assertTrue(false);

        }

        assertTrue( true );

I would expect this to print "SUCCESS" but instead I get a:
com.jayway.jsonpath.PathNotFoundException: Property ['userName'] not found in path $

This is being tested on:
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

**Comment by croteb** [comment]
I created a corresponding repo to display behavior here:
https://github.com/croteb/jsonpath-path-read-bug

**Comment by kallestenflo** [comment]
The read context is not a JSON object. You will have to call ```ctx.json()``` to pass the JSON model.

Here are some different alternatives:

```java
    @Test
    public void issue_84() {
        String JSON = "{\"userName\":\"tstark\"}";
        String PATH = "$.userName";
        String name;

        JsonPath compiledPath = JsonPath.compile(PATH);

        //Alternative 1 - ReadContext with compiled path
        name = JsonPath.parse(JSON).read(compiledPath);
        assertThat(name).isEqualTo("tstark");

        //Alternative 2 - ReadContext with string path (this will compile the path and cache it)
        name = JsonPath.parse(JSON).read(PATH);
        assertThat(name).isEqualTo("tstark");

        //Alternative 3 - Read using the JsonPath with JSON string
        name = compiledPath.read(JSON);
        assertThat(name).isEqualTo("tstark");

        //Alternative 4 - Read using the JsonPath with JSON model (the model depends on JsonProvider used)
        DocumentContext documentContext = JsonPath.parse(JSON);
        name = compiledPath.read(documentContext.json());
        assertThat(name).isEqualTo("tstark");

        //Alternative 5 - Read using simple static API
        name = JsonPath.read(JSON, PATH);
        assertThat(name).isEqualTo("tstark");
    }
```

Please ask questions here [google group](https://groups.google.com/forum/#!forum/jsonpath).

**Comment by kallestenflo** [comment]
Invalid usage.
