### ISSUE TITLE
Upgrade JSON-Smart dependency

### ISSUE THREAD

**Issue by ghost** [jayway/JsonPath#85]
## Issue
` Multiple dex files define Lorg/objectweb/asm/AnnotationVisitor;` error in Android dex compilation phase. When using JSON-Path with Mockito.

### Probable cause
The JSON-Smart dependency packages asm classes under default namespace.
See Issues:   
* https://code.google.com/p/json-smart/issues/detail?id=52 ( see last comment from project maintainer )
* https://code.google.com/p/json-smart/issues/detail?id=51

Can the JSON-Smart dependency version be upgraded to latest release ?

**Comment by kallestenflo** [comment]
We are running 2.1.1. This is the latest release http://search.maven.org/#search%7Cga%7C1%7Cjson-smart
/Kalle

**Comment by jaredsburrows** [comment]
Has anyone resolved this?

**Comment by jochenberger** [comment]
Should be resolved in json-smart 2.2 (see #108)

**Comment by jochenberger** [comment]
We're at 2.2 now.

**Comment by kallestenflo** [comment]
resolved in #108
