### ISSUE TITLE
ECCN for jayway JSON path

### ISSUE THREAD

**Issue by beurer** [jayway/JsonPath#87]
Hello,
We use jayway JSON path in our commercial product and therefore need to know the ECCN for it.
The ECCN is an international Export control and compliance number that is necessary for EVERY Export. Most of the european countries specify their goods according to the european commerce control list (EG dual-use list : http://ec.europa.eu/trade/import-and-ex ... -controls/).
So for export of a commercial Software using jayway JSON path ( or any other open source or OEM Software), we need to document the libs, on one side to comply with license obligations and on the other side the ECCNs for Export restrictions. Please note, as the US regulations also care about re-export of US items ( any stuff that contains US Content above a certain Limit), we need to specify both; the EU-ECCN and the US-ECCN and hopefully the US license exception that applies (e.g. TSU for open source).

So please specify the ECCN for jayway JSON path or answer the following questions:
- Country of origin ( where is jayway JSON path Software mainly developed)
- is there US Content in there? ( e.g. other open source libs)
- Is the SW designed or modified to use cryptography performing any cryptographic function other than authentication or digital signature? (y/n) 
–if yes,
-- key length symetric
-- Bit length asymmetric

Thanks and kind regards
Maria Beurer

**Comment by kallestenflo** [comment]
Hi,

* JsonPath is released under Apache Licens, version 2    
* JsonPath is mainly developed in Sweden
* It depends on the following projects (not sure of origin)
  * http://www.slf4j.org/ (logging)
  * One of the following JSON parsers
    * https://code.google.com/p/json-smart/ 
    * https://github.com/FasterXML/jackson
    * https://github.com/google/gson
* It does not use cryptography
