### ISSUE TITLE
How to match "(left instanceof Number && right instanceof Number)" in safeCompare

### ISSUE THREAD

**Issue by followyourheart** [jayway/JsonPath#90]
How to match "(left instanceof Number && right instanceof Number)" in safeCompare?

Thanks a lot.

**Comment by followyourheart** [comment]
when using "$.store.book[?(@.price > 12)].price", the left stands for 12. however, in safeCompare, the left is instance of String.  A Number is expected.

**Comment by kallestenflo** [comment]
The path "$.store.book[?(@.price > 12)].price" evaluates correctly when I
try it here <http://jsonpath.herokuapp.com/>.

Can you provide a sample JSON and Path so I understand your problem?

/Kalle

**Comment by followyourheart** [comment]
jsonStr = 
{
    "store": {
        "book": [
            {"price": "120"},
            {"price": 8.95},
            { "price": 12.99},
            {"price": 8.99 },
            { "price": 22.99}
        ],
    },
    "expensive": 10
}

jsonPath = "$.store.book[?(@.price <= 90)].price";

return: [120, 8.95, 12.99, 8.99, 22.99]

**Comment by kallestenflo** [comment]
Thanks! I will look into it.

**Comment by kallestenflo** [comment]
This is fixed and will be part of next release:

```
@Test
    public void issue_90() {

        String json = "{\n" +
                "    \"store\": {\n" +
                "        \"book\": [\n" +
                "            {\n" +
                "                \"price\": \"120\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"price\": 8.95\n" +
                "            },\n" +
                "            {\n" +
                "                \"price\": 12.99\n" +
                "            },\n" +
                "            {\n" +
                "                \"price\": 8.99\n" +
                "            },\n" +
                "            {\n" +
                "                \"price\": 22.99\n" +
                "            }\n" +
                "        ]\n" +
                "    },\n" +
                "    \"expensive\": 10\n" +
                "}";

        List<Double> numbers = JsonPath.read(json, "$.store.book[?(@.price <= 90)].price");

        assertThat(numbers).containsExactly(8.95D, 12.99D, 8.99D, 22.99D);
    }
```
