### ISSUE TITLE
Reaching path after filtering

### ISSUE THREAD

**Issue by mtyurt** [jayway/JsonPath#92]
I have the same issue as posted in this [question](http://stackoverflow.com/questions/30322086/pick-the-1st-filtered-result-in-jsonpath). The path is as follows:
```
$.store.book[?(@.category==fiction)].price
```
Filtering returns `LinkedHashMap`, but `.price` returns `JSONArray`. I tried `.price[0]` but `InvalidPathException` is thrown then. What is the solution to this problem?

**Comment by kallestenflo** [comment]
The class returned depends on which JsonProvider you are using. 

JsonSmartJsonProvider -> java.util.List
JacksonJsonProvider -> java.util.List
JacksonJsonNodeJsonProvider -> com.fasterxml.jackson.databind.node.ArrayNode
GsonJsonProvider -> com.google.gson.JsonArray

You can not extract the first result via the path. You will have to do something like this:

```java
List<Double> prices = JsonPath
   .parse(json)
   .read("$.store.book[?(@.category == 'fiction')].price");

Double firstPrice = prices.isEmpty() ? null : prices.get(0);
```
