### ISSUE TITLE
Matching for JSON objects/arrays not just strings

### ISSUE THREAD

**Issue by genman** [jayway/JsonPath#95]
I have a patch that allows you to match JSON fields to arrays or objects. Before I bother my company about approving a patch, I'd like to know if that is something you'd accept.

E.g. you can do this:

[?(@.foo == ["A", "B"])]
[?(@.foo == {"A": true})]

**Comment by kallestenflo** [comment]
Sounds great! Create a pull request and I will take a look.

I appreciate you contribution.

**Comment by genman** [comment]
https://github.com/jayway/JsonPath/pull/115
